/* PropBetEdge NFL — Dashboard v4 */
(() => {
  'use strict';

  const API = typeof NFL_API_GATEWAY !== 'undefined' ? NFL_API_GATEWAY : 'https://nfl-api.propbetedge.ai';
  const DEFAULT_EVENT='8c94552d022acec4a0458d70c19d3da9';
  const MARKETS=['player_pass_yds','player_reception_yds','player_receptions','player_rush_yds'];
  const state={loading:false,board:null,model:null,news:[],scores:null};
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
  const num=v=>{const n=Number(v);return Number.isFinite(n)?n:NaN};
  const fmt=(v,d=1)=>{const n=num(v);return Number.isFinite(n)?n.toFixed(d).replace(/\.0$/,''):'—'};
  const currentEvent=()=>new URLSearchParams(location.search).get('event')||localStorage.getItem('pbe_nfl_event')||DEFAULT_EVENT;
  const isPro=()=>Boolean(window.PBEPro?.state?.pro);
  const playerOf=x=>x?.player||x?.player_name||'';
  const bookOf=q=>q?.book||q?.book_title||q?.sportsbook||q?.book_key||'';
  const pointOf=q=>num(q?.point??q?.line);
  const marketLabel=m=>({player_pass_yds:'Passing Yards',player_reception_yds:'Receiving Yards',player_receptions:'Receptions',player_rush_yds:'Rushing Yards'}[m]||String(m||'').replace(/^player_/,'').replace(/_/g,' '));

  async function fetchJson(url){const r=await fetch(url,{cache:'no-store',headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}
  function event(){return state.board?.event||{}};
  function eventLabel(){const e=event(),a=e.away_team||e.away,h=e.home_team||e.home;return a&&h?`${a} @ ${h}`:'Selected NFL event';}
  function kickoff(){const e=event();return e.commence_time||e.start_time||e.game_time||null;}
  function fmtTime(v){if(!v)return'Time unavailable';const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v);return d.toLocaleString('en-US',{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});}
  function marketStats(){const q=state.board?.quotes||[];return{quotes:state.board?.quote_count??q.length,rows:state.board?.player_market_count??(state.board?.market_summary||[]).length,books:new Set(q.map(bookOf).filter(Boolean)).size,semantic:state.board?.source?.semantics||'UNAVAILABLE',provider:state.board?.source?.provider||'unknown'};}
  function currentTeams(){const e=event(),names=[e.away_team||e.away,e.home_team||e.home].filter(Boolean).map(String);const out=new Set();Object.values(window.NFL_TEAMS||{}).forEach(t=>{if(names.some(n=>n.toLowerCase()===String(t.name||'').toLowerCase()||n.toLowerCase().includes(String(t.city||'').toLowerCase())))out.add(t.abbr)});return out;}
  function relevantNews(){const teams=currentTeams();let rows=state.news.filter(a=>(a.teams||[]).some(t=>teams.has(String(t).toUpperCase())));if(rows.length<3)rows=[...rows,...state.news.filter(a=>!rows.includes(a))];return rows.sort((a,b)=>new Date(b.published_at||0)-new Date(a.published_at||0)).slice(0,6);}
  function timeAgo(v){if(!v)return'time unavailable';const d=new Date(v);if(Number.isNaN(d.getTime()))return'time unavailable';const h=Math.floor((Date.now()-d.getTime())/3600000);if(h<1)return'<1h ago';if(h<48)return`${h}h ago`;return`${Math.floor(h/24)}d ago`;}

  function dispersionRows(){const map=new Map();(state.board?.quotes||[]).forEach(q=>{const p=playerOf(q),m=q.market,pt=pointOf(q);if(!p||!m||!Number.isFinite(pt))return;const key=`${p}|${m}`;if(!map.has(key))map.set(key,{player:p,market:m,points:[],books:new Set()});map.get(key).points.push(pt);if(bookOf(q))map.get(key).books.add(bookOf(q));});return [...map.values()].map(r=>{const lo=Math.min(...r.points),hi=Math.max(...r.points);return{...r,lo,hi,spread:hi-lo};}).sort((a,b)=>b.spread-a.spread||b.books.size-a.books.size).slice(0,7);}
  function modelRows(){const rows=state.model?.models||state.model?.picks||state.model?.data||[];return(Array.isArray(rows)?rows:[]).filter(m=>m?.available!==false).sort((a,b)=>Math.abs(num(b.fair_line_gap_yards)||0)-Math.abs(num(a.fair_line_gap_yards)||0)).slice(0,5);}
  function scoreSemantic(){return String(state.scores?.source?.semantics||state.scores?.semantics||'SCHEDULE/UNAVAILABLE').toUpperCase();}

  function health(){const ms=marketStats();const newsOk=state.news.length>0,modelOk=isPro()&&modelRows().length>0;return `<div class="pbe24-health"><div class="pbe24-health-card"><div class="pbe24-health-label">Sportsbook market</div><div class="pbe24-health-value ${ms.semantic==='LIVE'?'green':''}">${esc(ms.semantic)}</div><div class="pbe24-health-copy">${esc(ms.provider)} · ${esc(ms.quotes)} quotes</div></div><div class="pbe24-health-card"><div class="pbe24-health-label">PBE model</div><div class="pbe24-health-value ${modelOk?'blue':isPro()?'red':'gold'}">${isPro()?(modelOk?'MODEL':'UNAVAILABLE'):'NFL PRO'}</div><div class="pbe24-health-copy">Server-gated production model</div></div><div class="pbe24-health-card"><div class="pbe24-health-label">NFL newsroom</div><div class="pbe24-health-value ${newsOk?'green':'red'}">${newsOk?'CURRENT':'UNAVAILABLE'}</div><div class="pbe24-health-copy">${state.news.length} current NFL stories loaded</div></div><div class="pbe24-health-card"><div class="pbe24-health-label">Score state</div><div class="pbe24-health-value blue">${esc(scoreSemantic())}</div><div class="pbe24-health-copy">Game Center enforces explicit LIVE semantics</div></div><div class="pbe24-health-card"><div class="pbe24-health-label">Account</div><div class="pbe24-health-value ${isPro()?'gold':''}">${isPro()?'NFL PRO':'FREE'}</div><div class="pbe24-health-copy">${isPro()?'Premium intelligence unlocked':'Sportsbook market remains available'}</div></div></div>`;}

  function gameCard(){const ms=marketStats();return `<aside class="pbe24-game"><div class="pbe24-game-head"><strong>Selected Game</strong><span>${esc(ms.semantic)} market</span></div><div class="pbe24-match"><div><div class="pbe24-matchup">${esc(eventLabel())}</div><div class="pbe24-kickoff">${esc(fmtTime(kickoff()))}</div></div></div><div class="pbe24-game-stats"><div class="pbe24-game-stat"><b class="green">${esc(ms.quotes)}</b><span>Quotes</span></div><div class="pbe24-game-stat"><b>${esc(ms.rows)}</b><span>Player markets</span></div><div class="pbe24-game-stat"><b>${esc(ms.books)}</b><span>Books</span></div></div><div class="pbe24-game-link"><button class="pbe24-btn primary" onclick="App.nav('propboard')">Open Props</button><button class="pbe24-btn" onclick="PBEEventSelector?.open()">Change Game</button></div></aside>`;}

  function signalPanels(){const dispersion=dispersionRows();const models=modelRows();return `<div class="pbe24-signal-grid"><section class="pbe24-panel"><div class="pbe24-panel-head"><strong>Cross-Book Dislocation</strong><span>CURRENT · line range</span></div><div class="pbe24-dispersion">${dispersion.length?dispersion.map(r=>`<div class="pbe24-disp-row"><div><div class="pbe24-disp-player" data-player="${esc(r.player)}">${esc(r.player)}</div><div class="pbe24-disp-prop">${esc(marketLabel(r.market))} · ${r.books.size} books</div></div><div class="pbe24-disp-range">${esc(fmt(r.lo,1))} – ${esc(fmt(r.hi,1))}</div><div class="pbe24-disp-gap">${esc(fmt(r.spread,1))}</div></div>`).join(''):'<div class="pbe24-empty">No multi-book line dispersion returned for the selected event.</div>'}</div></section><section class="pbe24-panel"><div class="pbe24-panel-head"><strong>Largest PBE Model Gaps</strong><span>${isPro()?'MODEL':'NFL PRO'}</span></div>${isPro()?`<div class="pbe24-models">${models.length?models.map(m=>{const gap=num(m.fair_line_gap_yards);return`<div class="pbe24-model"><div class="pbe24-model-top"><span class="pbe24-model-player" data-player="${esc(playerOf(m))}">${esc(playerOf(m))}</span><span class="pbe24-model-gap">${gap>0?'+':''}${esc(fmt(gap,1))}</span></div><div class="pbe24-model-meta">Market ${esc(fmt(m.market_consensus_line,1))} · fair ${esc(fmt(m.fair_line,1))} · ${esc(fmt(m.model_over_at_consensus_pct,1))}% model over · ${esc(String(m.decision_status||m.confidence||'MODEL').replace(/_/g,' '))}</div></div>`}).join(''):'<div class="pbe24-empty">No supported production model rows returned for the selected event.</div>'}</div>`:`<div class="pbe24-protease"><div><strong>Unlock the proprietary layer</strong><p>The sportsbook market is free. NFL Pro adds production fair lines, model probabilities, Market Watch, Simulator and SGP research.</p><button class="pbe24-btn gold" onclick="PBEPro.open('upgrade')">NFL Pro · $9.99/week</button></div></div>`}</section></div>`;}

  function tools(){const items=[['↗','Prop Board','CURRENT','Free cross-book sportsbook market.','propboard','current'],['◌','Market Watch','PRO','Watchlist, dispersion ranking and explicit local baseline movement.','marketwatch','pro'],['◫','Matchups','RESEARCH','Selected-event market, current news and historical team context.','matchups',''],['◈','Model Lab','PRO','Production PBE passing model audit and missing inputs.','picks','pro'],['⌁','Line Simulator','PRO','Move a line and derive sensitivity from fair line + predictive SD.','simulator','pro'],['⎇','SGP Lab','PRO','Build same-game research legs without faking correlation.','sgplab','pro'],['▥','Usage Research','BASELINE','2025 final role volume plus current team news.','usage',''],['◇','PropChain','BETA','News → entity → current market → model evidence map.','propchain',''],['◉','Game Center','EVENT','Selected event state, score semantics, market and news.','pbecast','current'],['＋','Injuries','NEWS','Current injury developments with official-status boundary.','injuries','current'],['⇄','Transactions','NEWS','Current trades, signings and roster movement.','trades','current'],['⬡','Teams','32 CLUBS','Franchise research and archive context.','teams','']];return `<div class="pbe24-tools">${items.map(i=>`<article class="pbe24-tool ${i[5]}" onclick="App.nav('${i[4]}')"><span class="pbe24-tool-tag">${esc(i[2])}</span><div class="pbe24-tool-icon">${i[0]}</div><h3>${esc(i[1])}</h3><p>${esc(i[3])}</p></article>`).join('')}</div>`;}

  function news(){const rows=relevantNews();return `<div class="pbe24-news-grid">${rows.length?rows.map(a=>`<article class="pbe24-news"><div class="pbe24-news-topic">${esc(String(a.topic_kind||'NEWS').toUpperCase())}</div><h3>${esc(a.title)}</h3><p>${esc(a.summary||'No summary available.')}</p><div class="pbe24-news-foot"><span class="pbe24-news-source">${esc(a.source||'source unavailable')} · ${esc(timeAgo(a.published_at))}</span>${a.url?`<a href="${esc(a.url)}">Open ↗</a>`:''}</div></article>`).join(''):'<div class="pbe24-empty" style="grid-column:1/-1">Current NFL newsroom unavailable.</div>'}</div>`;}
  function archives(){const rows=[['2025 Final Standings','Playoff seeds, divisions and final point differential.','standings'],['2025 Stats Archive','Final passing, rushing, receiving and defensive leaders.','stats'],['Season Archive','Champions, MVPs, awards and league leaders.','seasonhistory'],['Hall of Fame','Canton induction research.','hof'],['Records','All-time NFL record book and milestones.','records'],['Super Bowls','Every champion, final score, venue and MVP.','sb'],['Draft Research','Truth-first source review state until verified data is attached.','prospects'],['All 32 Teams','Franchise research directory.','teams']];return `<div class="pbe24-archive">${rows.map(r=>`<article class="pbe24-archive-card" onclick="App.nav('${r[2]}')"><strong>${esc(r[0])}</strong><span>${esc(r[1])}</span></article>`).join('')}</div>`;}

  function shell(){const ms=marketStats();return `<section class="pbe24-home"><header class="pbe24-hero"><div class="pbe24-hero-copy"><div class="pbe24-kicker">PROPBETEDGE NFL · FOOTBALL INTELLIGENCE OS</div><h1 class="pbe24-title">See the market.<br><em>Understand the game.</em></h1><div class="pbe24-copy">One operating system for current NFL sportsbook pricing, production PBE model context, matchup research, current news intelligence and the historical archive. Every layer keeps its provenance explicit: MARKET, MODEL, NEWS, SCHEDULE or HISTORICAL.</div><div class="pbe24-actions"><button class="pbe24-btn primary" onclick="App.nav('propboard')">Open Live Prop Board</button><button class="pbe24-btn" onclick="App.nav('matchups')">Research Matchup</button>${isPro()?'<button class="pbe24-btn gold" onclick="App.nav(\'marketwatch\')">Open NFL Pro</button>':'<button class="pbe24-btn gold" onclick="PBEPro.open(\'upgrade\')">Unlock NFL Pro</button>'}</div><div class="pbe24-chips"><span class="pbe24-chip ${ms.semantic==='LIVE'?'live':''}">MARKET ${esc(ms.semantic)}</span><span class="pbe24-chip ${isPro()?'pro':''}">${isPro()?'NFL PRO ACTIVE':'FREE MARKET ACCESS'}</span><span class="pbe24-chip">NO SYNTHETIC LIVE FALLBACK</span></div></div>${gameCard()}</header>${health()}<div class="pbe24-section-head"><div><h2>Where the market disagrees</h2><p>Current cross-book line dispersion beside the proprietary PBE model layer.</p></div><a href="javascript:void(0)" onclick="App.nav('marketwatch')">Market Watch →</a></div>${signalPanels()}<div class="pbe24-section-head"><div><h2>NFL Intelligence Workspace</h2><p>Current market tools, premium modeling workflows and truth-first research.</p></div><a href="javascript:void(0)" onclick="PBECommandPalette?.open()">Search everything →</a></div>${tools()}<div class="pbe24-section-head"><div><h2>Current NFL Intelligence</h2><p>Newsroom stories prioritized toward the selected matchup when possible.</p></div><a href="https://propbetedge.ai/news/nfl">NFL News →</a></div>${news()}<div class="pbe24-section-head"><div><h2>Research Archive</h2><p>Historical data is deliberately labeled and separated from current 2026 intelligence.</p></div></div>${archives()}</section>`;}

  function wirePlayers(){document.querySelectorAll('.pbe24-disp-player[data-player],.pbe24-model-player[data-player]').forEach(el=>el.addEventListener('click',e=>{e.stopPropagation();window.PBEPlayerResearch?.show(el.dataset.player)}));}
  function renderShell(){const vc=document.getElementById('view-container');if(vc){vc.innerHTML=shell();wirePlayers();}}
  async function render(){if(state.loading)return;state.loading=true;const vc=document.getElementById('view-container');if(!vc){state.loading=false;return;}vc.innerHTML='<section class="pbe24-home"><div class="pbe24-empty">Loading NFL Intelligence OS…</div></section>';try{const eventId=currentEvent();const [board,news,scores,model]=await Promise.all([fetchJson(`${API}/api/odds/board?event_id=${encodeURIComponent(eventId)}&markets=${encodeURIComponent(MARKETS.join(','))}`).catch(()=>null),fetchJson('/api/news-feed?limit=80').catch(()=>({articles:[]})),fetchJson(`${API}/api/scores`).catch(()=>null),isPro()?fetchJson(`${API}/api/picks/pass?event_id=${encodeURIComponent(eventId)}`).catch(()=>null):Promise.resolve(null)]);state.board=board;state.news=Array.isArray(news?.articles)?news.articles:[];state.scores=scores;state.model=model;renderShell();}catch(error){vc.innerHTML=`<section class="pbe24-home"><div class="pbe24-empty">Dashboard data unavailable: ${esc(error instanceof Error?error.message:String(error))}</div></section>`;}finally{state.loading=false;}}
  function install(){if(!window.App?.VIEWS)return false;App.VIEWS.home=render;window.HomeView={render};return true;}
  window.PBEDashboardV4={render,state};install();document.addEventListener('DOMContentLoaded',install,{once:true});window.addEventListener('pbe:event-changed',()=>{if(document.querySelector('.pbe24-home')&&!state.loading)render();});window.addEventListener('pbe:pro-state',()=>{if(document.querySelector('.pbe24-home')&&!state.loading)render();});
})();
