/* PropBetEdge NFL — Hall of Fame v2 */
(() => {
  'use strict';
  const state={search:'',pos:'all',decade:'all',sort:'newest'};
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
  const members=()=>Array.isArray(window.HOF_MEMBERS)?HOF_MEMBERS:[];
  function positions(){return [...new Set(members().map(m=>m.pos).filter(Boolean))].sort();}
  function decades(){return [...new Set(members().map(m=>Math.floor(Number(m.inducted)/10)*10).filter(Number.isFinite))].sort((a,b)=>b-a);}
  function latestYear(){const years=members().map(m=>Number(m.inducted)).filter(Number.isFinite);return years.length?Math.max(...years):null;}
  function filtered(){const q=state.search.trim().toLowerCase();const rows=members().filter(m=>{const posOk=state.pos==='all'||m.pos===state.pos;const decade=Number.isFinite(Number(m.inducted))?Math.floor(Number(m.inducted)/10)*10:null;const decadeOk=state.decade==='all'||String(decade)===String(state.decade);const qOk=!q||[m.name,m.teams,m.pos,m.era,m.note].some(v=>String(v||'').toLowerCase().includes(q));return posOk&&decadeOk&&qOk;});if(state.sort==='name')return rows.sort((a,b)=>a.name.localeCompare(b.name));if(state.sort==='oldest')return rows.sort((a,b)=>a.inducted-b.inducted||a.name.localeCompare(b.name));return rows.sort((a,b)=>b.inducted-a.inducted||a.name.localeCompare(b.name));}
  function summary(){const rows=filtered();const latest=latestYear();const recent=members().filter(m=>Number(m.inducted)>=2020).length;const teams=new Set(members().flatMap(m=>String(m.teams||'').split(',').map(x=>x.trim()).filter(Boolean))).size;return `<div class="pbe9-summary"><div class="pbe9-stat"><b>${rows.length}</b><span>Members in current view</span></div><div class="pbe9-stat"><b class="gold">${latest||'—'}</b><span>Latest induction class</span></div><div class="pbe9-stat"><b>${recent}</b><span>Inducted since 2020</span></div><div class="pbe9-stat"><b>${teams}</b><span>Team abbreviations represented</span></div></div>`;}
  function classes(){const rows=filtered();if(!rows.length)return'<div class="pbe9-empty">No Hall of Fame members match the current filters.</div>';const groups=new Map();rows.forEach(m=>{if(!groups.has(m.inducted))groups.set(m.inducted,[]);groups.get(m.inducted).push(m)});return [...groups.entries()].sort((a,b)=>state.sort==='oldest'?a[0]-b[0]:b[0]-a[0]).map(([year,list])=>`<section class="pbe9-class"><div class="pbe9-class-head"><div class="pbe9-year">${year}</div><span class="pbe9-class-count">${list.length} inducted</span><span class="pbe9-class-line"></span></div><div class="pbe9-member-grid">${list.map(m=>`<article class="pbe9-member" data-player="${esc(m.name)}"><div class="pbe9-member-top"><div><div class="pbe9-member-name">${esc(m.name)}</div><div class="pbe9-teams">${esc(m.teams||'Teams unavailable')}</div></div><span class="pbe9-position">${esc(m.pos||'HOF')}</span></div><div class="pbe9-era">${esc(m.era||'Era unavailable')}</div><div class="pbe9-note">${esc(m.note||'Hall of Fame profile note unavailable.')}</div></article>`).join('')}</div></section>`).join('');}
  function render(){const vc=document.getElementById('view-container');if(!vc)return;const all=members();if(!all.length){vc.innerHTML='<section class="pbe9-hof"><div class="pbe9-empty">Hall of Fame archive unavailable.</div></section>';return;}const latest=latestYear();vc.innerHTML=`<section class="pbe9-hof"><header class="pbe9-hero"><div><div class="pbe9-kicker">PRO FOOTBALL HALL OF FAME · CANTON ARCHIVE</div><h1 class="pbe9-title">The legends.<br><em>The classes. The eras.</em></h1><div class="pbe9-copy">Search the retained Hall of Fame member dataset by name, team, position, induction class or era. The latest class is determined from the dataset itself instead of being hardcoded into the UI.</div></div><aside class="pbe9-hero-side"><b>${all.length}</b><span>Hall of Fame members in this research dataset · latest class ${latest||'—'}</span></aside></header><div id="pbe9-summary">${summary()}</div><section class="pbe9-controls"><div class="pbe9-control-top"><input id="pbe9-search" class="pbe9-input" type="search" placeholder="Search legend, team, era…" value="${esc(state.search)}"><select id="pbe9-decade" class="pbe9-select"><option value="all">All decades</option>${decades().map(d=>`<option value="${d}" ${String(state.decade)===String(d)?'selected':''}>${d}s</option>`).join('')}</select><select id="pbe9-sort" class="pbe9-select"><option value="newest" ${state.sort==='newest'?'selected':''}>Newest classes</option><option value="oldest" ${state.sort==='oldest'?'selected':''}>Oldest classes</option><option value="name" ${state.sort==='name'?'selected':''}>Name A–Z</option></select></div><div class="pbe9-posbar"><button class="pbe9-pos ${state.pos==='all'?'active':''}" data-pos="all">All</button>${positions().map(p=>`<button class="pbe9-pos ${state.pos===p?'active':''}" data-pos="${esc(p)}">${esc(p)}</button>`).join('')}</div></section><div id="pbe9-classes">${classes()}</div></section>`;wire();}
  function refresh(){const s=document.getElementById('pbe9-summary');if(s)s.innerHTML=summary();const c=document.getElementById('pbe9-classes');if(c)c.innerHTML=classes();wireMembers();}
  function wire(){document.getElementById('pbe9-search')?.addEventListener('input',e=>{state.search=e.currentTarget.value||'';refresh()});document.getElementById('pbe9-decade')?.addEventListener('change',e=>{state.decade=e.currentTarget.value||'all';render()});document.getElementById('pbe9-sort')?.addEventListener('change',e=>{state.sort=e.currentTarget.value||'newest';render()});document.querySelectorAll('.pbe9-pos[data-pos]').forEach(b=>b.addEventListener('click',()=>{state.pos=b.dataset.pos||'all';render()}));wireMembers();}
  function wireMembers(){document.querySelectorAll('.pbe9-member[data-player]').forEach(el=>el.addEventListener('click',()=>{try{if(window.PlayerModal)PlayerModal.show(el.dataset.player)}catch(_){}}));}
  function install(){if(!window.App?.VIEWS)return false;App.VIEWS.hof=render;return true;}
  window.PBEHofV2={render,state};install();document.addEventListener('DOMContentLoaded',install,{once:true});
})();
