/* PropBetEdge NFL — factual Matchup Research
 * Current: selected sportsbook event + NEWS.
 * Historical: 2025 final standings context.
 * MODEL: PBE passing context for NFL Pro only. No hardcoded scheme score.
 */
(() => {
  'use strict';

  const API = typeof NFL_API_GATEWAY !== 'undefined' ? NFL_API_GATEWAY : 'https://nfl-api.propbetedge.ai';
  const DEFAULT_EVENT='8c94552d022acec4a0458d70c19d3da9';
  const state={loading:false,board:null,news:[],model:null,eventId:''};
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
  const num=v=>{const n=Number(v);return Number.isFinite(n)?n:NaN};
  const fmt=(v,d=1)=>{const n=num(v);return Number.isFinite(n)?n.toFixed(d).replace(/\.0$/,''):'—'};
  const isPro=()=>Boolean(window.PBEPro?.state?.pro);
  const currentEvent=()=>new URLSearchParams(location.search).get('event')||localStorage.getItem('pbe_nfl_event')||DEFAULT_EVENT;

  async function fetchJson(url){const r=await fetch(url,{cache:'no-store',headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}
  function event(){return state.board?.event||{}};
  function away(){const e=event();return e.away_team||e.away||'Away'}
  function home(){const e=event();return e.home_team||e.home||'Home'}
  function kickoff(){const e=event();return e.commence_time||e.start_time||e.game_time||null}
  function dateTime(v){if(!v)return'Time unavailable';const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v);return d.toLocaleString('en-US',{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});}
  function team(abbrOrName){const text=String(abbrOrName||'').toLowerCase();return Object.values(window.NFL_TEAMS||{}).find(t=>text===String(t.name||'').toLowerCase()||text===String(t.abbr||'').toLowerCase()||text.includes(String(t.city||'').toLowerCase())||text.includes(String(t.name||'').toLowerCase().split(' ').pop()))||null;}
  function crest(t,size=58){try{if(t?.abbr&&typeof teamCrest==='function')return teamCrest(t.abbr,size)}catch(_){}return `<strong style="color:#fff;font:900 15px 'Inter',sans-serif">${esc(t?.abbr||'NFL')}</strong>`;}

  function standingsRows(){const src=window.StandingsView?.STANDINGS||{};const out=[];Object.entries(src).forEach(([conf,divs])=>Object.entries(divs||{}).forEach(([div,rows])=>(rows||[]).forEach(r=>out.push({...r,conf,div}))));return out;}
  function standingFor(t){if(!t)return null;return standingsRows().find(r=>r.abbr===t.abbr||String(r.name||'').toLowerCase()===String(t.name||'').toLowerCase())||null;}
  function diff(r){return r?(Number(r.pf)||0)-(Number(r.pa)||0):NaN;}

  function newsFor(t){if(!t)return[];const abbr=String(t.abbr||'').toUpperCase(),name=String(t.name||'').toLowerCase(),city=String(t.city||'').toLowerCase();return state.news.filter(a=>(a.teams||[]).map(x=>String(x).toUpperCase()).includes(abbr)||`${a.title||''} ${a.summary||''}`.toLowerCase().includes(name)||`${a.title||''} ${a.summary||''}`.toLowerCase().includes(city)).sort((a,b)=>new Date(b.published_at||0)-new Date(a.published_at||0)).slice(0,5);}
  function injuryCount(t){return newsFor(t).filter(a=>String(a.topic_kind||'').toLowerCase()==='injury'||/injur|ankle|knee|hamstring|concussion|sidelined|out for/i.test(`${a.title||''} ${a.summary||''}`)).length;}
  function quoteStats(){const q=Array.isArray(state.board?.quotes)?state.board.quotes:[];const books=new Set(q.map(x=>x.book||x.book_title||x.book_key||x.sportsbook).filter(Boolean));return{quotes:state.board?.quote_count??q.length,markets:state.board?.player_market_count??(state.board?.market_summary||[]).length,books:books.size,semantics:state.board?.source?.semantics||'UNAVAILABLE'};}
  function modelRows(){const rows=state.model?.models||state.model?.picks||state.model?.data||[];return (Array.isArray(rows)?rows:[]).filter(x=>x?.available!==false);}

  function teamPanel(t,s){const d=diff(s);return `<section class="pbe16-panel"><div class="pbe16-panel-head"><strong>${esc(t?.name||'Team')} · 2025 Final Context</strong><span>HISTORICAL</span></div><div class="pbe16-context"><div class="pbe16-box"><b>${s?`${s.w}-${s.l}`:'—'}</b><span>2025 final record</span></div><div class="pbe16-box"><b class="${Number.isFinite(d)?d>=0?'pos':'neg':''}">${Number.isFinite(d)?`${d>0?'+':''}${d}`:'—'}</b><span>2025 point differential</span></div><div class="pbe16-box"><b>${s?.seed||'—'}</b><span>2025 playoff seed</span></div><div class="pbe16-box"><b>${esc(t?.sbWins??0)}</b><span>Super Bowl wins · franchise</span></div><div class="pbe16-note"><strong>Archive boundary:</strong> ${esc(s?.note||'2025 final standings are retained for historical context.')} Old coach/record snapshots are not relabeled as current 2026 facts.</div></div></section>`;}
  function newsPanel(t){const rows=newsFor(t);return `<section class="pbe16-panel"><div class="pbe16-panel-head"><strong>${esc(t?.abbr||'TEAM')} Current News</strong><span>NEWS · ${rows.length} matching</span></div><div class="pbe16-news">${rows.length?rows.map(a=>`<div class="pbe16-news-row"><a href="${esc(a.url||'#')}">${esc(a.title)}</a><div class="pbe16-news-meta">${esc(a.source||'source unavailable')} · ${esc(a.topic_kind||'news')}${String(a.topic_kind||'').toLowerCase()==='injury'?'<span class="pbe16-tag">INJURY</span>':''}</div></div>`).join(''):'<div class="pbe16-empty">No current newsroom stories matched this team.</div>'}</div></section>`;}
  /* Free tier previously got a single locked box with no indication of what the
     panel contains. The market rows the surface already loaded are shown with
     the model columns locked, so the shape of the tool is legible. */
  function lockedModelPanel(){
    const rows=[...new Map((state.board?.market_summary||[]).filter(r=>r?.market==='player_pass_yds').map(r=>[String(r.player||'').toLowerCase(),r])).values()].slice(0,6);
    if(!rows.length)return `<section class="pbe16-model"><div class="pbe16-panel-head"><strong>PBE Passing Context</strong><span>NFL PRO</span></div><div class="pbe16-empty">No supported passing-market rows are being returned for this event, so there is nothing to preview.</div></section>`;
    return `<section class="pbe16-model"><div class="pbe16-panel-head"><strong>PBE Passing Context</strong><span>NFL PRO</span></div>
      <div class="pbe16-model-grid">${rows.map(r=>`<article class="pbe16-model-card locked"><div class="pbe16-model-player">${esc(r.player||'Player')}</div><div class="pbe16-model-meta">Passing yards &middot; ${esc(r.book_count||0)} books</div><div class="pbe16-model-stats"><div class="pbe16-model-stat"><b>${esc(fmt(num(r.consensus_line),1))}</b><span>Market</span></div><div class="pbe16-model-stat"><b class="pbe-locked-value"></b><span>PBE fair</span></div><div class="pbe16-model-stat"><b class="pbe-locked-value"></b><span>Model gap</span></div></div></article>`).join('')}</div>
      <div class="pbe-lock-cta"><div class="pbe-lock-copy"><h3>PBE fair line and model gap are NFL Pro</h3><p>The sportsbook consensus above is current provider data. NFL Pro adds the modelled fair line, the gap against that consensus and the over probability for each supported passing market.</p></div><button class="pbe16-btn gold" onclick="PBEPro.open('upgrade')">Unlock NFL Pro &middot; $9.99/week</button></div>
    </section>`;
  }

  function modelPanel(){if(!isPro())return lockedModelPanel();const rows=modelRows();return `<section class="pbe16-model"><div class="pbe16-panel-head"><strong>PBE Passing Context</strong><span>MODEL · ${esc(state.model?.model_version||state.model?.lineage||'production')}</span></div>${rows.length?`<div class="pbe16-model-grid">${rows.map(m=>{const fair=num(m.fair_line),gap=num(m.fair_line_gap_yards),prob=num(m.model_over_at_consensus_pct),market=num(m.market_consensus_line);return `<article class="pbe16-model-card"><div class="pbe16-model-player">${esc(m.player||m.player_name||'Player')}</div><div class="pbe16-model-meta">Passing yards · ${esc(String(m.decision_status||m.confidence||'MODEL').replace(/_/g,' '))}</div><div class="pbe16-model-stats"><div class="pbe16-model-stat"><b>${esc(fmt(market,1))}</b><span>Market</span></div><div class="pbe16-model-stat"><b>${esc(fmt(fair,1))}</b><span>PBE fair</span></div><div class="pbe16-model-stat"><b class="green">${Number.isFinite(gap)&&gap>0?'+':''}${esc(fmt(gap,1))}</b><span>Model gap${Number.isFinite(prob)?` · ${esc(fmt(prob,1))}% over`:''}</span></div></div></article>`}).join('')}</div>`:'<div class="pbe16-empty">No supported production passing-model rows returned for the selected event.</div>'}</section>`;}

  function shell(){const at=team(away()),ht=team(home()),as=standingFor(at),hs=standingFor(ht),qs=quoteStats();return `<section class="pbe16-match"><header class="pbe16-hero"><div class="pbe16-top"><span class="pbe16-kicker">MATCHUP RESEARCH · SELECTED EVENT</span><span class="pbe16-semantics">MARKET ${esc(qs.semantics)} · ARCHIVE + NEWS CONTEXT</span></div><div class="pbe16-vs"><div class="pbe16-team"><div class="pbe16-crest">${crest(at,58)}</div><div class="pbe16-team-name">${esc(at?.name||away())}</div><div class="pbe16-team-sub">${esc(at?.conf||'')} ${esc(at?.div||'')} · ${esc(at?.stadium||'')}</div></div><div class="pbe16-center"><b>VS</b><span>${esc(dateTime(kickoff()))}</span></div><div class="pbe16-team"><div class="pbe16-crest">${crest(ht,58)}</div><div class="pbe16-team-name">${esc(ht?.name||home())}</div><div class="pbe16-team-sub">${esc(ht?.conf||'')} ${esc(ht?.div||'')} · ${esc(ht?.stadium||'')}</div></div></div><div class="pbe16-event"><strong>Truth contract:</strong> current sportsbook event + current NEWS + clearly labeled 2025 final team context. The recovered hardcoded scheme matchup score is not used.</div></header><div class="pbe16-summary"><div class="pbe16-stat"><b class="green">${esc(qs.quotes)}</b><span>Current sportsbook quotes</span></div><div class="pbe16-stat"><b>${esc(qs.markets)}</b><span>Current player markets</span></div><div class="pbe16-stat"><b>${esc(qs.books)}</b><span>Sportsbooks</span></div><div class="pbe16-stat"><b class="blue">${injuryCount(at)}</b><span>${esc(at?.abbr||'Away')} current injury stories</span></div><div class="pbe16-stat"><b class="blue">${injuryCount(ht)}</b><span>${esc(ht?.abbr||'Home')} current injury stories</span></div></div><div class="pbe16-compare">${teamPanel(at,as)}${teamPanel(ht,hs)}${newsPanel(at)}${newsPanel(ht)}</div>${modelPanel()}<div class="pbe16-audit"><strong>Blocked inputs:</strong> the recovered matchup worker’s scheme, blitz-rate, pressure-rate and position vulnerability tables are hardcoded internal MODEL metadata, not a verified 2026 defensive data feed, so this page does not present them as current matchup facts. Usage/target-share scoring also remains blocked until the random legacy implementation is replaced with factual usage data.</div></section>`;}

  async function render(){if(state.loading)return;state.loading=true;const vc=document.getElementById('view-container');if(!vc){state.loading=false;return;}vc.innerHTML='<section class="pbe16-match"><div class="pbe16-empty">Loading factual selected-event matchup context…</div></section>';try{state.eventId=currentEvent();const [board,news,model]=await Promise.all([fetchJson(`${API}/api/odds/board?event_id=${encodeURIComponent(state.eventId)}&markets=player_pass_yds,player_reception_yds,player_rush_yds`),fetchJson('/api/news-feed?limit=100').catch(()=>({articles:[]})),isPro()?fetchJson(`${API}/api/picks/pass?event_id=${encodeURIComponent(state.eventId)}`).catch(()=>null):Promise.resolve(null)]);state.board=board;state.news=Array.isArray(news?.articles)?news.articles:[];state.model=model;vc.innerHTML=shell();}catch(error){vc.innerHTML=`<section class="pbe16-match"><div class="pbe16-empty">Matchup context unavailable: ${esc(error instanceof Error?error.message:String(error))}</div></section>`;}finally{state.loading=false;}}
  function install(){if(!window.App?.VIEWS)return false;App.VIEWS.matchups=render;const anchor=document.getElementById('nav-propboard')||document.getElementById('nav-picks');if(anchor&&!document.getElementById('nav-matchups')){const a=document.createElement('a');a.className='nav-item';a.id='nav-matchups';a.href='javascript:void(0)';a.onclick=()=>App.nav('matchups');a.innerHTML='<span class="ni-icon">◫</span> Matchup Research';anchor.insertAdjacentElement('afterend',a);}return true;}
  window.PBEMatchupsV2={render,state};install();document.addEventListener('DOMContentLoaded',install,{once:true});window.addEventListener('pbe:pro-state',()=>{if(document.querySelector('.pbe16-match')&&!state.loading)render();});
})();
