/* PropBetEdge NFL — Records v2 */
(() => {
  'use strict';
  const state={cat:null,search:''};
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
  /* archive/records.js exposes classic-script lexical const bindings, not window props. */
  const records=()=>typeof NFL_RECORDS!=='undefined'&&NFL_RECORDS&&typeof NFL_RECORDS==='object'?NFL_RECORDS:(window.NFL_RECORDS||{});
  const milestones=()=>typeof NFL_MILESTONES!=='undefined'&&Array.isArray(NFL_MILESTONES)?NFL_MILESTONES:(Array.isArray(window.NFL_MILESTONES)?window.NFL_MILESTONES:[]);
  function cats(){return Object.keys(records());}
  function label(cat){return cat==='MILESTONES'?'Milestones':String(cat||'').charAt(0)+String(cat||'').slice(1).toLowerCase().replace(/_/g,' ');}
  function rows(){if(state.cat==='MILESTONES')return[];const q=state.search.trim().toLowerCase();return (records()[state.cat]||[]).filter(r=>!q||[r.record,r.holder,r.stat,r.team,r.year,r.note].some(v=>String(v||'').toLowerCase().includes(q)));}
  function filteredMilestones(){const q=state.search.trim().toLowerCase();return milestones().filter(m=>!q||[m.year,m.event].some(v=>String(v||'').toLowerCase().includes(q)));}
  function featured(){const list=rows().slice(0,3);if(!list.length)return'';return `<div class="pbe10-featured">${list.map((r,i)=>`<article class="pbe10-feature" data-player="${esc(r.holder)}"><span class="pbe10-feature-rank">${i+1}</span><div class="pbe10-feature-stat">${esc(r.record)}</div><div class="pbe10-feature-holder">${esc(r.holder)}</div><div class="pbe10-feature-desc">${esc(r.stat)}</div><div class="pbe10-feature-meta">${esc(r.team||'')} · ${esc(r.year||'')}</div></article>`).join('')}</div>`;}
  function recordGrid(){const list=rows();if(!list.length)return'<div class="pbe10-empty">No records match the current search in this category.</div>';return `${featured()}<div class="pbe10-grid">${list.slice(3).map(r=>`<article class="pbe10-card" data-player="${esc(r.holder)}"><div class="pbe10-card-stat">${esc(r.record)}</div><div class="pbe10-card-holder">${esc(r.holder)}</div><div class="pbe10-card-desc">${esc(r.stat)}</div><div class="pbe10-card-meta">${esc(r.team||'')} · ${esc(r.year||'')}</div>${r.note?`<div class="pbe10-card-note">${esc(r.note)}</div>`:''}</article>`).join('')}</div>`;}
  function timeline(){const list=filteredMilestones().slice().sort((a,b)=>(Number(a.year)||0)-(Number(b.year)||0));if(!list.length)return'<div class="pbe10-empty">No milestones match the current search.</div>';return `<section class="pbe10-timeline">${list.map(m=>`<div class="pbe10-time-row"><div class="pbe10-time-year">${esc(m.year)}</div><div class="pbe10-time-axis"><span class="pbe10-time-dot"></span></div><div class="pbe10-time-copy">${esc(m.event)}</div></div>`).join('')}</section>`;}
  function body(){return state.cat==='MILESTONES'?timeline():recordGrid();}
  function render(){const vc=document.getElementById('view-container');if(!vc)return;if(!state.cat)state.cat=cats()[0]||'MILESTONES';const total=cats().reduce((n,c)=>n+(records()[c]||[]).length,0);vc.innerHTML=`<section class="pbe10-records"><header class="pbe10-hero"><div class="pbe10-kicker">NFL ALL-TIME RECORD BOOK</div><h1 class="pbe10-title">Numbers that<br><em>outlived the moment.</em></h1><div class="pbe10-copy">Search all-time record holders across passing, rushing, receiving, defense, scoring, special teams and coaching, or switch to the historical milestone timeline. This is reference/archive intelligence — not a live statistical feed.</div><div class="pbe10-badges"><span class="pbe10-badge red">ALL-TIME RECORDS</span><span class="pbe10-badge">${total} record entries</span><span class="pbe10-badge">${milestones().length} milestones</span></div></header><section class="pbe10-controls"><div class="pbe10-tabs">${[...cats(),'MILESTONES'].map(c=>`<button class="pbe10-tab ${state.cat===c?'active':''}" data-cat="${esc(c)}">${esc(label(c))}</button>`).join('')}</div><input id="pbe10-search" class="pbe10-search" type="search" placeholder="Search holder, team, record, year or milestone…" value="${esc(state.search)}"></section><div id="pbe10-body">${body()}</div></section>`;wire();}
  function refresh(){const host=document.getElementById('pbe10-body');if(host)host.innerHTML=body();wirePlayers();}
  function wire(){document.querySelectorAll('.pbe10-tab[data-cat]').forEach(b=>b.addEventListener('click',()=>{state.cat=b.dataset.cat;state.search='';render()}));document.getElementById('pbe10-search')?.addEventListener('input',e=>{state.search=e.currentTarget.value||'';refresh()});wirePlayers();}
  function wirePlayers(){document.querySelectorAll('[data-player]').forEach(el=>el.addEventListener('click',()=>{try{if(window.PlayerModal)PlayerModal.show(el.dataset.player)}catch(_){}}));}
  function install(){if(!window.App?.VIEWS)return false;App.VIEWS.records=render;return true;}
  window.PBERecordsV2={render,state};install();document.addEventListener('DOMContentLoaded',install,{once:true});
})();