/* PropBetEdge NFL — SGP Lab v2
 * Current legs are factual sportsbook quotes.
 * No combined probability / edge / payout is calculated without correlation and actual book SGP repricing.
 */
(() => {
  'use strict';

  const API = typeof NFL_API_GATEWAY !== 'undefined' ? NFL_API_GATEWAY : 'https://nfl-api.propbetedge.ai';
  const DEFAULT_EVENT='8c94552d022acec4a0458d70c19d3da9';
  const BATCH_SIZE=5;
  const MARKETS=['player_pass_yds','player_pass_completions','player_pass_attempts','player_pass_tds','player_pass_interceptions','player_reception_yds','player_receptions','player_rush_yds','player_rush_attempts','player_anytime_td'];
  const state={loading:false,board:null,model:null,rows:[],legs:[],search:'',market:'all'};
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
  const num=v=>{const n=Number(v);return Number.isFinite(n)?n:NaN};
  const fmt=(v,d=1)=>{const n=num(v);return Number.isFinite(n)?n.toFixed(d).replace(/\.0$/,''):'—'};
  const price=v=>{const n=num(v);return Number.isFinite(n)?`${n>0?'+':''}${Math.round(n)}`:'—'};
  const currentEvent=()=>new URLSearchParams(location.search).get('event')||localStorage.getItem('pbe_nfl_event')||DEFAULT_EVENT;
  const isPro=()=>Boolean(window.PBEPro?.state?.pro);
  const playerOf=x=>x?.player||x?.player_name||'';
  const bookOf=q=>q?.book||q?.book_title||q?.sportsbook||q?.book_key||'';
  const sideOf=q=>String(q?.direction||q?.outcome||q?.side||q?.name||'').toUpperCase();
  const pointOf=q=>num(q?.point??q?.line);
  const priceOf=q=>num(q?.price??q?.american_odds??q?.odds);
  const marketLabel=m=>({player_pass_yds:'Passing Yards',player_pass_completions:'Pass Completions',player_pass_attempts:'Pass Attempts',player_pass_tds:'Passing TDs',player_pass_interceptions:'Interceptions',player_reception_yds:'Receiving Yards',player_receptions:'Receptions',player_rush_yds:'Rushing Yards',player_rush_attempts:'Rush Attempts',player_anytime_td:'Anytime TD'}[m]||String(m||'').replace(/^player_/,'').replace(/_/g,' '));

  async function fetchJson(url){const r=await fetch(url,{cache:'no-store',headers:{Accept:'application/json'}});if(!r.ok){const t=await r.text().catch(()=> '');throw new Error(`${r.status}${t?` · ${t.slice(0,120)}`:''}`);}return r.json();}
  function batch(values,size){const out=[];for(let i=0;i<values.length;i+=size)out.push(values.slice(i,i+size));return out;}
  function median(values){const a=values.map(num).filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return NaN;const i=Math.floor(a.length/2);return a.length%2?a[i]:(a[i-1]+a[i])/2;}
  function bestQuote(quotes,side){const rows=quotes.filter(q=>sideOf(q).includes(side));if(!rows.length)return null;return [...rows].sort((a,b)=>{const ap=pointOf(a),bp=pointOf(b);if(Number.isFinite(ap)&&Number.isFinite(bp)&&ap!==bp)return side==='OVER'?ap-bp:bp-ap;return priceOf(b)-priceOf(a);})[0];}
  function merge(parts){const valid=parts.filter(Boolean);if(!valid.length)throw new Error('No Prop Board batches returned');const out={...valid[0],quotes:[],market_summary:[]},qs=new Set(),ss=new Set();valid.forEach(p=>{(p.quotes||[]).forEach(q=>{const k=[bookOf(q),q.market,playerOf(q),sideOf(q),q.point??q.line,q.price??q.odds??q.american_odds].join('|');if(!qs.has(k)){qs.add(k);out.quotes.push(q)}});(p.market_summary||[]).forEach(s=>{const k=`${playerOf(s)}|${s.market}`;if(!ss.has(k)){ss.add(k);out.market_summary.push(s)}})});return out;}
  async function loadBoard(){const parts=[];for(const group of batch(MARKETS,BATCH_SIZE)){try{parts.push(await fetchJson(`${API}/api/odds/board?event_id=${encodeURIComponent(currentEvent())}&markets=${encodeURIComponent(group.join(','))}`));}catch(_){const settled=await Promise.allSettled(group.map(m=>fetchJson(`${API}/api/odds/board?event_id=${encodeURIComponent(currentEvent())}&markets=${encodeURIComponent(m)}`)));settled.forEach(r=>{if(r.status==='fulfilled')parts.push(r.value)});}}return merge(parts);}

  function buildRows(board){const map=new Map();const ensure=(p,m)=>{const k=`${p.toLowerCase()}|${m}`;if(!map.has(k))map.set(k,{key:k,player:p,market:m,quotes:[],summary:null});return map.get(k)};(board.market_summary||[]).forEach(s=>{const p=playerOf(s);if(p&&s.market)ensure(p,s.market).summary=s});(board.quotes||[]).forEach(q=>{const p=playerOf(q);if(p&&q.market)ensure(p,q.market).quotes.push(q)});return [...map.values()].map(r=>{let consensus=num(r.summary?.consensus_line??r.summary?.line);if(!Number.isFinite(consensus))consensus=median(r.quotes.map(pointOf));return{...r,consensus,bestOver:bestQuote(r.quotes,'OVER'),bestUnder:bestQuote(r.quotes,'UNDER'),books:[...new Set(r.quotes.map(bookOf).filter(Boolean))]};});}
  function modelMap(){const m=new Map();const rows=state.model?.models||state.model?.picks||state.model?.data||[];(Array.isArray(rows)?rows:[]).forEach(x=>{const p=playerOf(x);if(p)m.set(p.toLowerCase(),x)});return m;}
  function modelForLeg(leg){if(leg.market!=='player_pass_yds')return null;return modelMap().get(leg.player.toLowerCase())||null;}
  function legKey(player,market,side){return `${player.toLowerCase()}|${market}|${side}`;}
  function hasLeg(player,market,side){return state.legs.some(l=>l.id===legKey(player,market,side));}
  function addLeg(row,side){const quote=side==='OVER'?row.bestOver:row.bestUnder;if(!quote)return;const id=legKey(row.player,row.market,side);if(hasLeg(row.player,row.market,side))return;const opposite=side==='OVER'?'UNDER':'OVER';state.legs=state.legs.filter(l=>l.id!==legKey(row.player,row.market,opposite));state.legs.push({id,player:row.player,market:row.market,side,point:pointOf(quote),price:priceOf(quote),book:bookOf(quote),consensus:row.consensus});if(state.legs.length>6)state.legs.shift();renderShell();}
  function removeLeg(id){state.legs=state.legs.filter(l=>l.id!==id);renderShell();}
  function visible(){const q=state.search.trim().toLowerCase();return state.rows.filter(r=>(!q||`${r.player} ${marketLabel(r.market)}`.toLowerCase().includes(q))&&(state.market==='all'||r.market===state.market));}
  function eventLabel(){const e=state.board?.event||{},a=e.away_team||e.away,h=e.home_team||e.home;return a&&h?`${a} @ ${h}`:'Selected NFL event';}

  function marketRow(r){return `<div class="pbe23-market-row"><div><div class="pbe23-player">${esc(r.player)}</div><div class="pbe23-prop">${esc(marketLabel(r.market))} · consensus ${esc(fmt(r.consensus,1))} · ${r.books.length} books</div></div><button class="pbe23-leg-btn over" data-player="${esc(r.player)}" data-market="${esc(r.market)}" data-side="OVER" ${r.bestOver?'':'disabled'}>Over ${r.bestOver?`${esc(fmt(pointOf(r.bestOver),1))} ${esc(price(priceOf(r.bestOver)))}`:'—'}</button><button class="pbe23-leg-btn under" data-player="${esc(r.player)}" data-market="${esc(r.market)}" data-side="UNDER" ${r.bestUnder?'':'disabled'}>Under ${r.bestUnder?`${esc(fmt(pointOf(r.bestUnder),1))} ${esc(price(priceOf(r.bestUnder)))}`:'—'}</button></div>`;}

  function checks(){
    const legs=state.legs,checks=[];
    const duplicatePlayerMarket=new Set(),conflicts=[];legs.forEach(l=>{const k=`${l.player.toLowerCase()}|${l.market}`;if(duplicatePlayerMarket.has(k))conflicts.push(k);duplicatePlayerMarket.add(k)});
    const books=new Set(legs.map(l=>l.book).filter(Boolean));
    checks.push({type:conflicts.length?'bad':'ok',title:conflicts.length?'Conflicting player-market legs':'No direct Over/Under conflict',copy:conflicts.length?'The ticket contains mutually opposing selections on the same player/market.':'The builder prevents direct Over + Under duplicates for the same player/market.'});
    checks.push({type:books.size>1?'warn':'ok',title:books.size>1?'Best legs come from multiple books':'Current best legs share a book',copy:books.size>1?`Best individual quotes currently span ${books.size} books. A real same-game parlay must be repriced by one sportsbook.`:`Current selected best-leg quotes point to ${[...books][0]||'no book yet'}. The book can still reprice the SGP.`});
    checks.push({type:'warn',title:'Correlation model unavailable',copy:'PropBetEdge does not multiply independent probabilities or fabricate same-game correlation. Combined fair probability is intentionally unavailable.'});
    checks.push({type:'warn',title:'Actual SGP quote unavailable',copy:'Individual leg prices are not a valid substitute for the sportsbook’s repriced same-game parlay offer.'});
    return checks;
  }

  function modelBox(){if(!state.legs.length)return'';const rows=state.legs.map(l=>({leg:l,model:modelForLeg(l)}));return `<div class="pbe23-model-box"><strong>Per-leg PBE support</strong>${rows.map(({leg,model})=>`<div class="pbe23-model-row"><span>${esc(leg.player)} · ${esc(marketLabel(leg.market))} ${esc(leg.side)} ${esc(fmt(leg.point,1))}</span><b>${model?`FAIR ${esc(fmt(model.fair_line,1))} · ${esc(fmt(model.model_over_at_consensus_pct,1))}% OVER`:'MODEL UNAVAILABLE'}</b></div>`).join('')}<div class="pbe23-no-combine"><strong>No combined edge:</strong> supported per-leg model context does not create a valid joint probability without a tested correlation model. PropBetEdge leaves the combined number blank instead of pretending independence.</div></div>`;}

  function ticket(){if(!state.legs.length)return `<div class="pbe23-ticket-empty">Add current sportsbook legs from the market list. The lab will validate the construction without inventing a combined fair probability.</div>`;return `<div class="pbe23-ticket">${state.legs.map(l=>`<article class="pbe23-leg"><button class="pbe23-remove" data-remove="${esc(l.id)}">×</button><div class="pbe23-leg-player">${esc(l.player)}</div><div class="pbe23-leg-meta">${esc(marketLabel(l.market))} · ${esc(l.book||'book unavailable')} · individual ${esc(price(l.price))}</div><span class="pbe23-leg-side ${l.side==='UNDER'?'under':''}">${esc(l.side)} ${esc(fmt(l.point,1))}</span></article>`).join('')}<div class="pbe23-checks">${checks().map(c=>`<div class="pbe23-check ${c.type==='bad'?'bad':c.type==='warn'?'warn':''}"><span class="pbe23-check-icon">${c.type==='bad'?'!':c.type==='warn'?'△':'✓'}</span><div><strong>${esc(c.title)}</strong><span>${esc(c.copy)}</span></div></div>`).join('')}</div>${modelBox()}<div style="display:flex;gap:6px;margin-top:9px"><button class="pbe23-btn" id="pbe23-clear">Clear ticket</button><button class="pbe23-btn green" onclick="App.nav('propboard')">Back to Prop Board</button></div></div>`;}

  function shell(){const markets=[...new Set(state.rows.map(r=>r.market))].sort();const rows=visible();return `<section class="pbe23-sgp"><header class="pbe23-hero"><div><div class="pbe23-kicker">NFL PRO · SAME-GAME RESEARCH WORKSPACE</div><h1 class="pbe23-title">Build the legs.<br><em>Don’t fake the correlation.</em></h1><div class="pbe23-copy">SGP Lab assembles current sportsbook legs from one selected NFL event, checks construction conflicts and shows PBE model support where production coverage exists. It deliberately does not calculate a combined edge, fair probability or payout without a tested correlation model and the sportsbook’s actual repriced SGP quote.</div></div><aside class="pbe23-status"><b>${esc(eventLabel())}</b><span>${state.rows.length} current player-market rows · ${state.legs.length} selected legs · correlation unavailable</span></aside></header><div class="pbe23-contract"><strong>SGP contract:</strong> individual odds are not multiplied and called a fair same-game price. Same-event outcomes can be correlated, and sportsbooks can reprice parlays. Until PropBetEdge has a backtested joint model or actual SGP provider quote, combined probability/edge stays UNAVAILABLE.</div>${!isPro()?`<div class="pbe23-prowall"><div><strong>NFL Pro SGP Lab</strong><p>Build and audit same-game research tickets with current sportsbook legs and supported PBE model context.</p><button class="pbe23-btn gold" onclick="PBEPro.open('upgrade')">Unlock NFL Pro · $9.99/week</button></div></div>`:`<div class="pbe23-layout"><section class="pbe23-panel"><div class="pbe23-panel-head"><strong>Current Leg Market</strong><span>LIVE sportsbook quotes</span></div><div class="pbe23-tools"><input id="pbe23-search" class="pbe23-input" placeholder="Search player or prop…" value="${esc(state.search)}"><select id="pbe23-market" class="pbe23-select"><option value="all">All markets</option>${markets.map(m=>`<option value="${esc(m)}" ${state.market===m?'selected':''}>${esc(marketLabel(m))}</option>`).join('')}</select></div><div class="pbe23-market-list">${rows.length?rows.map(marketRow).join(''):'<div class="pbe23-empty">No current market rows match these filters.</div>'}</div></section><section class="pbe23-panel"><div class="pbe23-panel-head"><strong>Research Ticket</strong><span>${state.legs.length}/6 legs</span></div><div id="pbe23-ticket">${ticket()}</div></section></div>`}</section>`;}

  function renderShell(){const vc=document.getElementById('view-container');if(!vc)return;vc.innerHTML=shell();wire();}
  function wire(){document.getElementById('pbe23-search')?.addEventListener('input',e=>{state.search=e.currentTarget.value||'';renderShell()});document.getElementById('pbe23-market')?.addEventListener('change',e=>{state.market=e.currentTarget.value||'all';renderShell()});document.querySelectorAll('.pbe23-leg-btn[data-player]').forEach(btn=>btn.addEventListener('click',()=>{const row=state.rows.find(r=>r.player===btn.dataset.player&&r.market===btn.dataset.market);if(row)addLeg(row,btn.dataset.side);}));document.querySelectorAll('[data-remove]').forEach(btn=>btn.addEventListener('click',()=>removeLeg(btn.dataset.remove)));document.getElementById('pbe23-clear')?.addEventListener('click',()=>{state.legs=[];renderShell()});}

  async function render(){if(state.loading)return;state.loading=true;const vc=document.getElementById('view-container');if(!vc){state.loading=false;return;}vc.innerHTML='<section class="pbe23-sgp"><div class="pbe23-empty">Loading current same-game leg market…</div></section>';try{const [board,model]=await Promise.all([loadBoard(),isPro()?fetchJson(`${API}/api/picks/pass?event_id=${encodeURIComponent(currentEvent())}`).catch(()=>null):Promise.resolve(null)]);state.board=board;state.model=model;state.rows=buildRows(board);state.legs=[];vc.innerHTML=shell();wire();}catch(error){vc.innerHTML=`<section class="pbe23-sgp"><div class="pbe23-empty">SGP Lab unavailable: ${esc(error instanceof Error?error.message:String(error))}</div></section>`;}finally{state.loading=false;}}
  function install(){if(!window.App?.VIEWS)return false;App.VIEWS.sgplab=render;const sim=document.getElementById('nav-simulator')||document.getElementById('nav-picks');if(sim&&!document.getElementById('nav-sgplab')){const a=document.createElement('a');a.className='nav-item';a.id='nav-sgplab';a.href='javascript:void(0)';a.onclick=()=>App.nav('sgplab');a.innerHTML='<span class="ni-icon">⎇</span> SGP Lab <span class="nav-badge" style="color:#d8b75b;background:rgba(216,183,91,.06)">PRO</span>';sim.insertAdjacentElement('afterend',a);}return true;}
  window.PBESGPLab={render,state};install();document.addEventListener('DOMContentLoaded',install,{once:true});window.addEventListener('pbe:event-changed',()=>{state.legs=[];if(document.querySelector('.pbe23-sgp')&&!state.loading)render();});window.addEventListener('pbe:pro-state',()=>{if(document.querySelector('.pbe23-sgp')&&!state.loading)render();});
})();
