/* PropBetEdge NFL — Line Simulator v2
 * MODEL DERIVED from production fair_line + predictive_sd.
 * This does not re-run the production model or claim independent validation.
 */
(() => {
  'use strict';

  const API = typeof NFL_API_GATEWAY !== 'undefined' ? NFL_API_GATEWAY : 'https://nfl-api.propbetedge.ai';
  const DEFAULT_EVENT='8c94552d022acec4a0458d70c19d3da9';
  const state={loading:false,model:null,board:null,selected:null,lineByPlayer:new Map()};
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
  const num=v=>{const n=Number(v);return Number.isFinite(n)?n:NaN};
  const fmt=(v,d=1)=>{const n=num(v);return Number.isFinite(n)?n.toFixed(d).replace(/\.0$/,''):'—'};
  const currentEvent=()=>new URLSearchParams(location.search).get('event')||localStorage.getItem('pbe_nfl_event')||DEFAULT_EVENT;
  const isPro=()=>Boolean(window.PBEPro?.state?.pro);
  async function fetchJson(url){const r=await fetch(url,{cache:'no-store',headers:{Accept:'application/json'}});if(!r.ok){const e=new Error(`HTTP ${r.status}`);e.status=r.status;throw e;}return r.json();}

  function erf(x){
    const sign=x<0?-1:1;const a=Math.abs(x);const t=1/(1+0.3275911*a);
    const y=1-(((((1.061405429*t-1.453152027)*t)+1.421413741)*t-0.284496736)*t+0.254829592)*t*Math.exp(-a*a);
    return sign*y;
  }
  function normalCdf(z){return .5*(1+erf(z/Math.sqrt(2)));}
  function overProbability(line,fair,sd){if(!Number.isFinite(line)||!Number.isFinite(fair)||!Number.isFinite(sd)||sd<=0)return NaN;return Math.max(0,Math.min(100,(1-normalCdf((line-fair)/sd))*100));}
  function rows(){const raw=state.model?.models||state.model?.picks||state.model?.data||[];return (Array.isArray(raw)?raw:[]).filter(m=>m?.available!==false&&Number.isFinite(num(m.fair_line))&&Number.isFinite(num(m.predictive_sd))&&num(m.predictive_sd)>0);}
  function playerName(m){return m?.player||m?.player_name||'Player';}
  function selectedRow(){const list=rows();if(!list.length)return null;if(!state.selected||!list.some(m=>playerName(m)===state.selected))state.selected=playerName(list[0]);return list.find(m=>playerName(m)===state.selected)||list[0];}
  function currentLine(m){const key=playerName(m);if(state.lineByPlayer.has(key))return state.lineByPlayer.get(key);const market=num(m.market_consensus_line);const fair=num(m.fair_line);const line=Number.isFinite(market)?market:fair;state.lineByPlayer.set(key,line);return line;}
  function eventLabel(){const e=state.board?.event||{};const away=e.away_team||e.away,home=e.home_team||e.home;return away&&home?`${away} @ ${home}`:'Selected NFL event';}

  function proWall(){return `<div class="pbe20-prowall"><div><strong>NFL Pro Line Simulator</strong><p>The simulator uses proprietary production model outputs, so the interactive probability layer is available to NFL Pro subscribers. Free users can still see the current sportsbook Prop Board.</p><button class="pbe20-btn gold" onclick="PBEPro.open('upgrade')">Unlock NFL Pro · $9.99/week</button><button class="pbe20-btn" style="margin-left:6px" onclick="App.nav('propboard')">View free Prop Board</button></div></div>`;}

  function scenarioRows(m){const market=num(m.market_consensus_line),fair=num(m.fair_line),sd=num(m.predictive_sd),center=Number.isFinite(market)?market:fair;const values=[center-20,center-10,center,center+10,center+20].map(v=>Math.max(0,Math.round(v*2)/2));const seen=new Set();return values.filter(v=>!seen.has(v)&&seen.add(v)).map(line=>{const p=overProbability(line,fair,sd);return `<div class="pbe20-scenario ${Math.abs(line-center)<.01?'current':''}"><div class="pbe20-scenario-line">${esc(fmt(line,1))}</div><div class="pbe20-scenario-bar"><div class="pbe20-scenario-fill" style="width:${Number.isFinite(p)?p.toFixed(1):0}%"></div></div><div class="pbe20-scenario-prob">${esc(fmt(p,1))}%</div></div>`}).join('');}

  function workspace(){
    const m=selectedRow();if(!m)return `<div class="pbe20-empty">The production model returned no rows with a valid fair line and predictive standard deviation for this event. No simulator is fabricated.</div>`;
    const fair=num(m.fair_line),sd=num(m.predictive_sd),market=num(m.market_consensus_line),line=currentLine(m),prob=overProbability(line,fair,sd),base=num(m.model_over_at_consensus_pct),gap=fair-line;
    const min=Math.max(0,Math.floor((Math.min(fair,Number.isFinite(market)?market:fair)-Math.max(40,sd))*2)/2);
    const max=Math.ceil((Math.max(fair,Number.isFinite(market)?market:fair)+Math.max(40,sd))*2)/2;
    return `<div class="pbe20-workspace"><section class="pbe20-panel"><div class="pbe20-panel-head"><strong>Interactive Line Sensitivity</strong><span>MODEL DERIVED</span></div><div class="pbe20-control"><div class="pbe20-player-name">${esc(playerName(m))}</div><div class="pbe20-player-meta">Passing yards · fair ${esc(fmt(fair,1))} · predictive SD ${esc(fmt(sd,1))} · ${esc(String(m.decision_status||m.confidence||'MODEL').replace(/_/g,' '))}</div><div class="pbe20-line-display"><div class="pbe20-metric"><b>${esc(fmt(market,1))}</b><span>Current market consensus</span></div><div class="pbe20-metric"><b class="blue">${esc(fmt(fair,1))}</b><span>Production PBE fair line</span></div><div class="pbe20-metric"><b class="green">${gap>0?'+':''}${esc(fmt(gap,1))}</b><span>Fair minus selected line</span></div></div><div class="pbe20-slider-wrap"><div class="pbe20-slider-top"><strong>Move the sportsbook line</strong><input id="pbe20-line-input" class="pbe20-line-input" type="number" step="0.5" min="${min}" max="${max}" value="${line}"></div><input id="pbe20-range" class="pbe20-range" type="range" step="0.5" min="${min}" max="${max}" value="${line}"><div class="pbe20-range-label"><span>${min}</span><span>PBE fair ${esc(fmt(fair,1))}</span><span>${max}</span></div><div class="pbe20-prob"><div class="pbe20-prob-value">${esc(fmt(prob,1))}%</div><div class="pbe20-prob-copy">Derived model probability of finishing <strong>OVER ${esc(fmt(line,1))}</strong> using the production fair line as the distribution mean and the production predictive standard deviation. ${Number.isFinite(base)&&Number.isFinite(market)?`At the current consensus ${esc(fmt(market,1))}, the production response reports ${esc(fmt(base,1))}% over.`:''}</div></div><div class="pbe20-bar"><span class="pbe20-bar-dot" style="left:${Number.isFinite(prob)?prob.toFixed(1):50}%"></span></div></div></div></section><section class="pbe20-panel"><div class="pbe20-panel-head"><strong>Line Ladder</strong><span>Same model · different line</span></div><div class="pbe20-scenarios">${scenarioRows(m)}</div></section></div>`;
  }

  function shell(){const list=rows();return `<section class="pbe20-sim"><header class="pbe20-hero"><div><div class="pbe20-kicker">NFL PRO · MODEL-DERIVED TOOL</div><h1 class="pbe20-title">Move the line.<br><em>Watch probability move.</em></h1><div class="pbe20-copy">Line Simulator explores the sensitivity of the production passing model to a different sportsbook threshold. It is deliberately not presented as a separate Monte Carlo engine: the probability is derived from the existing PBE fair line and predictive standard deviation.</div></div><aside class="pbe20-status"><b>${esc(eventLabel())}</b><span>${isPro()?`${list.length} production rows available · server-gated model access`:'NFL Pro required · current sportsbook board remains free'}</span></aside></header><div class="pbe20-derived"><strong>MODEL DERIVED:</strong> changing the line does not re-run opponent, workload, injury, weather or other model inputs. It holds the production fair line and predictive SD fixed and recomputes the normal-distribution over probability at the selected threshold.</div>${isPro()?`${list.length?`<nav class="pbe20-tabs">${list.map(m=>`<button class="pbe20-player-tab ${playerName(m)===state.selected?'active':''}" data-player="${esc(playerName(m))}">${esc(playerName(m))}</button>`).join('')}</nav>`:''}<div id="pbe20-workspace">${workspace()}</div><div class="pbe20-audit"><div class="pbe20-audit-item"><b>Fair line</b><span>Production model point estimate, unchanged while you move the sportsbook threshold.</span></div><div class="pbe20-audit-item"><b>Predictive SD</b><span>Production uncertainty parameter used by the current passing model probability calculation.</span></div><div class="pbe20-audit-item"><b>Derived probability</b><span>Normal CDF sensitivity calculation at the selected line. Not separately trained or backtested.</span></div><div class="pbe20-audit-item"><b>No fake correlations</b><span>This tool simulates one supported passing-yard threshold at a time. It does not invent SGP correlation.</span></div></div>`:proWall()}</section>`;}

  function updateLine(value){const m=selectedRow();if(!m)return;const n=Number(value);if(!Number.isFinite(n))return;state.lineByPlayer.set(playerName(m),Math.round(n*2)/2);const host=document.getElementById('pbe20-workspace');if(host)host.innerHTML=workspace();wireWorkspace();}
  function wireWorkspace(){const range=document.getElementById('pbe20-range'),input=document.getElementById('pbe20-line-input');range?.addEventListener('input',e=>updateLine(e.currentTarget.value));input?.addEventListener('change',e=>updateLine(e.currentTarget.value));}
  function wire(){document.querySelectorAll('.pbe20-player-tab[data-player]').forEach(btn=>btn.addEventListener('click',()=>{state.selected=btn.dataset.player;const vc=document.getElementById('view-container');if(vc)vc.innerHTML=shell();wire();}));wireWorkspace();}

  async function render(){if(state.loading)return;state.loading=true;const vc=document.getElementById('view-container');if(!vc){state.loading=false;return;}vc.innerHTML='<section class="pbe20-sim"><div class="pbe20-empty">Opening NFL Pro Line Simulator…</div></section>';try{const eventId=currentEvent();const [board,model]=await Promise.all([fetchJson(`${API}/api/odds/board?event_id=${encodeURIComponent(eventId)}&markets=player_pass_yds`).catch(()=>null),isPro()?fetchJson(`${API}/api/picks/pass?event_id=${encodeURIComponent(eventId)}`).catch(()=>null):Promise.resolve(null)]);state.board=board;state.model=model;const list=rows();if(list.length&&!state.selected)state.selected=playerName(list[0]);vc.innerHTML=shell();wire();}catch(error){vc.innerHTML=`<section class="pbe20-sim"><div class="pbe20-empty">Simulator unavailable: ${esc(error instanceof Error?error.message:String(error))}</div></section>`;}finally{state.loading=false;}}

  function install(){if(!window.App?.VIEWS)return false;App.VIEWS.simulator=render;const lab=document.getElementById('nav-picks');if(lab&&!document.getElementById('nav-simulator')){const a=document.createElement('a');a.className='nav-item';a.id='nav-simulator';a.href='javascript:void(0)';a.onclick=()=>App.nav('simulator');a.innerHTML='<span class="ni-icon">⌁</span> Line Simulator <span class="nav-badge" style="color:#d8b75b;background:rgba(216,183,91,.06)">PRO</span>';lab.insertAdjacentElement('afterend',a);}return true;}
  window.PBELineSimulator={render,state};install();document.addEventListener('DOMContentLoaded',install,{once:true});window.addEventListener('pbe:pro-state',()=>{if(document.querySelector('.pbe20-sim')&&!state.loading)render();});window.addEventListener('pbe:event-changed',()=>{if(document.querySelector('.pbe20-sim')&&!state.loading){state.selected=null;state.lineByPlayer.clear();render();}});
})();
