/* PropBetEdge NFL — Standings v2 */
(() => {
  'use strict';
  const state={conf:'all',search:''};
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
  const crest=(abbr,size=25)=>{try{if(typeof teamCrest==='function')return teamCrest(abbr,size)}catch(_){}return `<strong style="color:#fff;font:900 11px 'Barlow Condensed',sans-serif">${esc(abbr)}</strong>`};
  const source=()=>window.StandingsView?.STANDINGS||{};
  const sourceMeta=()=>window.StandingsView?.source||{};
  const record=t=>`${t.w}-${t.l}${Number(t.t)>0?`-${t.t}`:''}`;
  function teams(){const out=[];Object.entries(source()).forEach(([conf,divs])=>Object.entries(divs||{}).forEach(([div,rows])=>(rows||[]).forEach(row=>out.push({...row,conf,div}))));return out;}
  function filtered(){const q=state.search.trim().toLowerCase();return teams().filter(t=>(state.conf==='all'||t.conf===state.conf)&&(!q||[t.name,t.abbr,t.conf,t.div,t.note].some(v=>String(v||'').toLowerCase().includes(q))));}
  function summary(){const rows=filtered();const playoff=rows.filter(t=>t.playoff).length;const div=rows.filter(t=>t.division).length;const points=rows.reduce((a,t)=>a+(Number(t.pf)||0),0);const best=rows.length?[...rows].sort((a,b)=>b.pct-a.pct||b.pf-a.pf)[0]:null;return `<div class="pbe7-summary"><div class="pbe7-stat"><b>${rows.length}</b><span>Teams in current view</span></div><div class="pbe7-stat"><b class="gold">${playoff}</b><span>2025 playoff teams</span></div><div class="pbe7-stat"><b>${div}</b><span>Division winners</span></div><div class="pbe7-stat"><b class="green">${best?record(best):'—'}</b><span>Best record in view</span></div><div class="pbe7-stat"><b>${points.toLocaleString()}</b><span>Points scored in view</span></div></div>`;}
  function seedPanel(conf){const rows=teams().filter(t=>t.conf===conf&&t.seed).sort((a,b)=>a.seed-b.seed);return `<section class="pbe7-seeds"><div class="pbe7-panel-head"><strong>${conf} Playoff Field</strong><span>Official seeds · 2025 final</span></div><div class="pbe7-seed-list">${rows.map(t=>`<div class="pbe7-seed-row" data-team="${esc(t.abbr)}"><div class="pbe7-seed-num">${t.seed}</div><div>${crest(t.abbr,25)}</div><div><div class="pbe7-seed-name">${esc(t.name)}</div><div class="pbe7-seed-meta">${esc(t.div)} · ${t.division?'division winner':'wild card'}</div></div><div class="pbe7-seed-record">${record(t)}</div></div>`).join('')}</div></section>`;}
  function divisionHtml(conf,div,rows){const filteredRows=rows.filter(t=>{const q=state.search.trim().toLowerCase();return !q||[t.name,t.abbr,t.note].some(v=>String(v||'').toLowerCase().includes(q))});if(!filteredRows.length)return'';return `<section class="pbe7-division"><div class="pbe7-div-head"><strong>${esc(conf)} ${esc(div)}</strong><span>2025 final</span></div>${filteredRows.map(t=>{const diff=(Number(t.pf)||0)-(Number(t.pa)||0);return `<div class="pbe7-team-row ${t.division?'divlead':''}" data-team="${esc(t.abbr)}"><div class="pbe7-team-seed ${t.playoff?'playoff':''}">${t.seed||'—'}</div><div>${crest(t.abbr,24)}</div><div><div class="pbe7-team-name">${esc(t.name)}</div><div class="pbe7-team-note">${esc(t.note||'')}</div></div><div class="pbe7-metric"><b class="win">${record(t)}</b><span>REC</span></div><div class="pbe7-metric mobile-hide"><b>${Number(t.pct).toFixed(3)}</b><span>PCT</span></div><div class="pbe7-metric hide-mid mobile-hide"><b>${t.pf}</b><span>PF</span></div><div class="pbe7-metric hide-mid mobile-hide"><b class="pbe7-diff ${diff>=0?'pos':'neg'}">${diff>0?'+':''}${diff}</b><span>DIFF</span></div></div>`}).join('')}</section>`;}
  function conferences(){const confs=state.conf==='all'?['AFC','NFC']:[state.conf];const src=source();const q=state.search.trim().toLowerCase();return confs.map(conf=>{const divisions=['East','North','South','West'].map(div=>divisionHtml(conf,div,src?.[conf]?.[div]||[])).filter(Boolean);if(!divisions.length)return'';return `<section class="pbe7-conf"><div class="pbe7-conf-title"><div><h2>${conf}</h2><p>${conf==='AFC'?'American Football Conference':'National Football Conference'} · verified regular-season final</p></div><span class="pbe7-archive">VERIFIED</span></div><div class="pbe7-divisions">${divisions.join('')}</div></section>`}).join('')||`<div class="pbe7-empty">No standings rows match “${esc(q)}”.</div>`;}
  function render(){const vc=document.getElementById('view-container');if(!vc)return;const rows=teams();if(!rows.length){vc.innerHTML='<section class="pbe7-standings"><div class="pbe7-empty">Standings archive unavailable.</div></section>';return;}const meta=sourceMeta();vc.innerHTML=`<section class="pbe7-standings"><header class="pbe7-hero"><div><div class="pbe7-kicker">2025 NFL REGULAR SEASON · VERIFIED FINAL</div><h1 class="pbe7-title">The playoff picture.<br><em>Frozen accurately.</em></h1><div class="pbe7-copy">Official 2025 regular-season records, division winners, playoff seeds, points for and scoring differential. Source: ${esc(meta.provider||'NFL.com')} · verified ${esc(meta.verifiedAt||'2026-08-29')}.</div><span class="pbe7-archive">VERIFIED · 2025 FINAL</span></div><aside class="pbe7-hero-side"><strong>32</strong><span>Official final records · ties preserved · playoff seeds verified</span></aside></header><div id="pbe7-summary">${summary()}</div><nav class="pbe7-controls"><button class="pbe7-btn ${state.conf==='all'?'active':''}" data-conf="all">All NFL</button><button class="pbe7-btn ${state.conf==='AFC'?'active':''}" data-conf="AFC">AFC</button><button class="pbe7-btn ${state.conf==='NFC'?'active':''}" data-conf="NFC">NFC</button><input id="pbe7-search" class="pbe7-search" type="search" placeholder="Search team or final-season note…" value="${esc(state.search)}"></nav><div class="pbe7-playoff">${seedPanel('AFC')}${seedPanel('NFC')}</div><div id="pbe7-confs">${conferences()}</div></section>`;wire();}
  function refresh(){const s=document.getElementById('pbe7-summary');if(s)s.innerHTML=summary();const c=document.getElementById('pbe7-confs');if(c)c.innerHTML=conferences();wireTeams();}
  function wire(){document.querySelectorAll('.pbe7-btn[data-conf]').forEach(b=>b.addEventListener('click',()=>{state.conf=b.dataset.conf||'all';render()}));document.getElementById('pbe7-search')?.addEventListener('input',e=>{state.search=e.currentTarget.value||'';refresh()});wireTeams();}
  function wireTeams(){document.querySelectorAll('[data-team]').forEach(el=>el.addEventListener('click',()=>{const abbr=el.dataset.team;try{if(window.PBETeamsV2)PBETeamsV2.openTeam(abbr);else if(window.TeamsView?.showTeam)TeamsView.showTeam(abbr)}catch(_){}}));}
  function install(){if(!window.App?.VIEWS)return false;App.VIEWS.standings=render;return true;}
  window.PBEStandingsV2={render,state};install();document.addEventListener('DOMContentLoaded',install,{once:true});
})();