/* PropBetEdge NFL — Usage Research v2
 * Historical role baseline from 2025 final stats + CURRENT NEWS.
 * Current 2026 target share/usage remains unavailable until factual pipeline replaces legacy random worker.
 */
(() => {
  'use strict';

  const API = typeof NFL_API_GATEWAY !== 'undefined' ? NFL_API_GATEWAY : 'https://nfl-api.propbetedge.ai';
  const DEFAULT_EVENT='8c94552d022acec4a0458d70c19d3da9';
  const state={loading:false,board:null,news:[]};
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
  const num=v=>{const n=Number(v);return Number.isFinite(n)?n:NaN};
  const currentEvent=()=>new URLSearchParams(location.search).get('event')||localStorage.getItem('pbe_nfl_event')||DEFAULT_EVENT;
  async function fetchJson(url){const r=await fetch(url,{cache:'no-store',headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}

  function event(){return state.board?.event||{}};
  function teamByName(name){const text=String(name||'').toLowerCase();return Object.values(window.NFL_TEAMS||{}).find(t=>text===String(t.name||'').toLowerCase()||text===String(t.abbr||'').toLowerCase()||text.includes(String(t.city||'').toLowerCase())||text.includes(String(t.name||'').toLowerCase().split(' ').pop()))||null;}
  function selectedTeams(){const e=event();return [teamByName(e.away_team||e.away),teamByName(e.home_team||e.home)].filter(Boolean);}
  function crest(t,size=30){try{if(t?.abbr&&typeof teamCrest==='function')return teamCrest(t.abbr,size)}catch(_){}return `<strong style="color:#fff;font:900 11px 'Barlow Condensed',sans-serif">${esc(t?.abbr||'NFL')}</strong>`;}

  function statsSource(key){return window.StatsView?.STATS?.[key]||null;}
  function rowsAsObjects(key){const cat=statsSource(key);if(!cat)return[];const headers=cat.headers||[];return (cat.rows||[]).map(row=>{const obj={};headers.forEach((h,i)=>obj[String(h).toUpperCase()]=row[i]);obj.__row=row;return obj;});}
  function value(obj,...names){for(const n of names){const key=String(n).toUpperCase();if(obj[key]!=null)return obj[key];}return'—';}
  function categoryRows(team,key){if(!team)return[];return rowsAsObjects(key).filter(r=>String(value(r,'TEAM')).toUpperCase()===team.abbr).slice(0,5);}
  function roleConfig(key){return {
    passing:{title:'Passing Volume',primary:['ATT','ATT'],secondary:['YDS','YDS'],third:['TD','TD']},
    rushing:{title:'Rushing Volume',primary:['ATT','ATT'],secondary:['YDS','YDS'],third:['TD','TD']},
    receiving:{title:'Receiving Volume',primary:['REC','REC'],secondary:['YDS','YDS'],third:['TD','TD']}
  }[key];}

  function roleRows(team,key){const cfg=roleConfig(key),rows=categoryRows(team,key);if(!rows.length)return'<div class="pbe21-empty">No 2025 final rows for this team/category in the retained stats archive.</div>';return `<div class="pbe21-role-list">${rows.map((r,i)=>`<div class="pbe21-role" data-player="${esc(value(r,'PLAYER'))}"><div class="pbe21-rank">${i+1}</div><div><div class="pbe21-player">${esc(value(r,'PLAYER'))}</div><div class="pbe21-player-team">${esc(team.abbr)} · 2025 final</div></div><div class="pbe21-role-stat"><b>${esc(value(r,cfg.primary[0]))}</b><span>${cfg.primary[1]}</span></div><div class="pbe21-role-stat"><b>${esc(value(r,cfg.secondary[0]))}</b><span>${cfg.secondary[1]}</span></div><div class="pbe21-role-stat mobile-hide"><b>${esc(value(r,cfg.third[0]))}</b><span>${cfg.third[1]}</span></div></div>`).join('')}</div>`;}

  function teamPanel(team){return `<section class="pbe21-team"><header class="pbe21-team-head"><div class="pbe21-crest">${crest(team,31)}</div><div><div class="pbe21-team-name">${esc(team.name)}</div><div class="pbe21-team-sub">HISTORICAL ROLE BASELINE · 2025 FINAL</div></div></header>${['passing','rushing','receiving'].map(key=>`<section class="pbe21-category"><div class="pbe21-category-head"><strong>${roleConfig(key).title}</strong><span>2025 FINAL · NOT CURRENT SHARE</span></div>${roleRows(team,key)}</section>`).join('')}</section>`;}

  function teamNews(teams){const abbrs=new Set(teams.map(t=>t.abbr));const names=teams.map(t=>String(t.name).toLowerCase());return state.news.filter(a=>(a.teams||[]).some(x=>abbrs.has(String(x).toUpperCase()))||names.some(n=>`${a.title||''} ${a.summary||''}`.toLowerCase().includes(n))).sort((a,b)=>new Date(b.published_at||0)-new Date(a.published_at||0)).slice(0,12);}
  function isInjury(a){return String(a.topic_kind||'').toLowerCase()==='injury'||/injur|ankle|knee|hamstring|concussion|sidelined|out for/i.test(`${a.title||''} ${a.summary||''}`);}
  function isRole(a){const topic=String(a.topic_kind||'').toLowerCase();return ['lineup','trade','signing','transaction','return'].includes(topic)||/starter|starting|depth chart|role|rotation|signed|trade|activated|return/i.test(`${a.title||''} ${a.summary||''}`);}
  function impact(a){const n=num(a.impact_score);return Number.isFinite(n)?n:0;}

  function newsPanel(teams){const rows=teamNews(teams);return `<section class="pbe21-current"><div class="pbe21-panel-head"><strong>Current Role Context</strong><span>NEWS · not usage telemetry</span></div><div class="pbe21-news-grid">${rows.length?rows.map(a=>`<article class="pbe21-news"><div class="pbe21-news-top"><span class="pbe21-news-topic">${esc(String(a.topic_kind||'news').toUpperCase())}</span><span class="pbe21-impact">${impact(a)||'—'}</span></div><a href="${esc(a.url||'#')}">${esc(a.title)}</a>${a.summary?`<div class="pbe21-news-copy">${esc(a.summary)}</div>`:''}<div class="pbe21-tags">${(a.teams||[]).slice(0,3).map(t=>`<span class="pbe21-tag">${esc(t)}</span>`).join('')}${(a.players||[]).slice(0,3).map(p=>`<span class="pbe21-tag">${esc(p)}</span>`).join('')}</div></article>`).join(''):'<div class="pbe21-empty" style="grid-column:1/-1">No current newsroom stories matched the selected teams.</div>'}</div></section>`;}

  function summary(teams){const baselinePlayers=new Set();teams.forEach(t=>['passing','rushing','receiving'].forEach(key=>categoryRows(t,key).forEach(r=>baselinePlayers.add(String(value(r,'PLAYER'))))));const news=teamNews(teams);return `<div class="pbe21-summary"><div class="pbe21-stat"><b>${baselinePlayers.size}</b><span>2025 baseline players shown</span></div><div class="pbe21-stat"><b class="green">${news.length}</b><span>Current team news stories</span></div><div class="pbe21-stat"><b>${news.filter(isInjury).length}</b><span>Current injury-context stories</span></div><div class="pbe21-stat"><b>${news.filter(isRole).length}</b><span>Current role / roster stories</span></div><div class="pbe21-stat"><b class="gold">OFF</b><span>Current target-share telemetry</span></div></div>`;}

  function shell(){const teams=selectedTeams(),e=event(),away=e.away_team||e.away||'Away',home=e.home_team||e.home||'Home';return `<section class="pbe21-usage"><header class="pbe21-hero"><div><div class="pbe21-kicker">USAGE RESEARCH · TRUTH-FIRST BASELINE</div><h1 class="pbe21-title">Role context.<br><em>Without fake share.</em></h1><div class="pbe21-copy">Usage Research combines factual 2025 final player-volume baselines for the selected matchup with current PropBetEdge NEWS context. It deliberately does not surface current target share, route participation or role certainty until a factual 2026 usage pipeline replaces the retired random legacy worker.</div></div><aside class="pbe21-status"><b>${esc(away)} @ ${esc(home)}</b><span>2025 final volume baseline + current NEWS · current target-share telemetry unavailable</span></aside></header><div class="pbe21-warning"><strong>Blocked on purpose:</strong> the recovered target-share worker used hardcoded baselines and random behavior. This page will not display that output as current usage intelligence. Reception totals below are historical receptions, not target share.</div>${summary(teams)}<div class="pbe21-grid">${teams.length?teams.map(teamPanel).join(''):'<div class="pbe21-empty" style="grid-column:1/-1">Selected event teams could not be resolved against the retained NFL team directory.</div>'}</div>${newsPanel(teams)}<div class="pbe21-boundary"><div class="pbe21-bound ready"><b>2025 final volume</b><span>Passing attempts, rushing attempts and receiving volume come from the retained final archive.</span></div><div class="pbe21-bound ready"><b>Current news context</b><span>Injury, lineup, transaction and role stories come from the current newsroom adapter.</span></div><div class="pbe21-bound blocked"><b>2026 target share</b><span>Unavailable until factual play/target telemetry is attached.</span></div><div class="pbe21-bound blocked"><b>Role certainty score</b><span>Not generated from random or hardcoded inputs. It remains unavailable.</span></div></div></section>`;}

  function wirePlayers(){document.querySelectorAll('.pbe21-role[data-player]').forEach(row=>row.addEventListener('click',()=>window.PBEPlayerResearch?.show(row.dataset.player)));}
  async function render(){if(state.loading)return;state.loading=true;const vc=document.getElementById('view-container');if(!vc){state.loading=false;return;}vc.innerHTML='<section class="pbe21-usage"><div class="pbe21-empty">Loading selected-matchup usage baseline…</div></section>';try{const eventId=currentEvent();const [board,news]=await Promise.all([fetchJson(`${API}/api/odds/board?event_id=${encodeURIComponent(eventId)}&markets=player_pass_yds`).catch(()=>null),fetchJson('/api/news-feed?limit=100').catch(()=>({articles:[]}))]);state.board=board;state.news=Array.isArray(news?.articles)?news.articles:[];vc.innerHTML=shell();wirePlayers();}catch(error){vc.innerHTML=`<section class="pbe21-usage"><div class="pbe21-empty">Usage Research unavailable: ${esc(error instanceof Error?error.message:String(error))}</div></section>`;}finally{state.loading=false;}}
  function install(){if(!window.App?.VIEWS)return false;App.VIEWS.usage=render;const sim=document.getElementById('nav-simulator')||document.getElementById('nav-picks');if(sim&&!document.getElementById('nav-usage')){const a=document.createElement('a');a.className='nav-item';a.id='nav-usage';a.href='javascript:void(0)';a.onclick=()=>App.nav('usage');a.innerHTML='<span class="ni-icon">▥</span> Usage Research <span class="nav-badge" style="color:#55d68c;background:rgba(85,214,140,.06)">BASELINE</span>';sim.insertAdjacentElement('afterend',a);}return true;}
  window.PBEUsageV2={render,state};install();document.addEventListener('DOMContentLoaded',install,{once:true});window.addEventListener('pbe:event-changed',()=>{if(document.querySelector('.pbe21-usage')&&!state.loading)render();});
})();
