-- PropBetEdge NFL Player Prop Engine v1
--
-- Algorithm #2 is intentionally separate from the game-market picker.
-- v1 supports the production passing-yards projection model only. The schema
-- is market-extensible, but unsupported markets must not be synthesized.
--
-- Invariants:
--   * every issued decision freezes player / market / book / line / price,
--     projection distribution, selector version and model snapshot;
--   * bootstrap tracking decisions can never be reclassified as official;
--   * official issuance requires a promoted + trained selector champion;
--   * one open decision per event/player/market; replacements are atomic;
--   * receipt ledger is append-only and chained with SHA-256;
--   * RLS is enabled with no anon policies. Service role only.

begin;

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.nfl_prop_selector_models (
  version bigint generated by default as identity primary key,
  market text not null,
  projection_model text not null,
  config jsonb not null default '{}'::jsonb,
  trained boolean not null default false,
  promoted boolean not null default false,
  training_rows integer not null default 0 check (training_rows >= 0),
  trained_through_week integer,
  backtest_clv_beat_pct numeric,
  backtest_brier numeric,
  backtest_units numeric,
  promoted_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  constraint nfl_prop_selector_config_object check (jsonb_typeof(config) = 'object')
);

create unique index if not exists nfl_prop_one_promoted_selector_per_market
  on public.nfl_prop_selector_models (market)
  where promoted = true;

alter table public.nfl_prop_selector_models enable row level security;

insert into public.nfl_prop_selector_models (
  market, projection_model, config, trained, promoted, training_rows, notes
)
select
  'player_pass_yds',
  'pbe-passing-production',
  jsonb_build_object(
    'source', 'hand_set_selector_prior',
    'min_edge', 0.04,
    'min_ev_pct', 5.0,
    'min_books', 4,
    'confidence_a_edge', 0.075,
    'confidence_b_edge', 0.055,
    'stake_floor_units', 0.5,
    'stake_cap_units', 2.0,
    'kelly_fraction', 0.25,
    'early_bird_min_hours', 12,
    'locked_max_hours', 4,
    'distribution', 'normal_from_production_fair_line_and_predictive_sd'
  ),
  false,
  true,
  0,
  'v1 selector priors; production passing projection input; not trained'
where not exists (
  select 1 from public.nfl_prop_selector_models where market = 'player_pass_yds'
);

create table if not exists public.nfl_prop_picks (
  id uuid primary key default gen_random_uuid(),
  event_id text not null,
  season integer not null,
  week integer not null,
  kickoff_ts timestamptz not null,
  player_name text not null,
  player_key text not null,
  market text not null,
  side text not null check (side in ('OVER','UNDER','YES','NO')),
  book text not null,
  book_key text,
  market_line numeric,
  market_price integer not null check (market_price <> 0),
  opposite_price integer check (opposite_price is null or opposite_price <> 0),
  model_fair_line numeric not null,
  predictive_sd numeric not null check (predictive_sd > 0),
  model_prob numeric not null check (model_prob >= 0 and model_prob <= 1),
  market_prob numeric check (market_prob is null or (market_prob >= 0 and market_prob <= 1)),
  edge_pct numeric,
  ev_pct numeric,
  stake_units numeric not null default 0 check (stake_units >= 0),
  confidence_bucket text check (confidence_bucket is null or confidence_bucket in ('A','B','C')),
  projection_model_version text,
  selector_version bigint not null references public.nfl_prop_selector_models(version) on delete restrict,
  phase text not null check (phase in ('early_bird','locked')),
  publication_scope text not null check (publication_scope in ('tracking','official')),
  status text not null default 'open' check (status in ('open','graded','killed','superseded')),
  model_snapshot jsonb not null,
  created_at timestamptz not null default now(),
  closed_at timestamptz,
  constraint nfl_prop_pick_snapshot_object check (jsonb_typeof(model_snapshot) = 'object' and model_snapshot <> '{}'::jsonb),
  constraint nfl_prop_pick_team_market_line check (market_line is not null)
);

alter table public.nfl_prop_picks enable row level security;

create index if not exists nfl_prop_picks_scope_kickoff_idx
  on public.nfl_prop_picks (publication_scope, kickoff_ts desc);
create index if not exists nfl_prop_picks_player_idx
  on public.nfl_prop_picks (player_key, market, kickoff_ts desc);
create unique index if not exists nfl_prop_one_open_pick_per_market
  on public.nfl_prop_picks (event_id, player_key, market)
  where status = 'open';

create or replace function public.nfl_prop_freeze_issuance()
returns trigger
language plpgsql
as $$
begin
  if row(
    old.event_id, old.season, old.week, old.kickoff_ts,
    old.player_name, old.player_key, old.market, old.side,
    old.book, old.book_key, old.market_line, old.market_price, old.opposite_price,
    old.model_fair_line, old.predictive_sd, old.model_prob, old.market_prob,
    old.edge_pct, old.ev_pct, old.stake_units, old.confidence_bucket,
    old.projection_model_version, old.selector_version, old.phase,
    old.publication_scope, old.model_snapshot, old.created_at
  ) is distinct from row(
    new.event_id, new.season, new.week, new.kickoff_ts,
    new.player_name, new.player_key, new.market, new.side,
    new.book, new.book_key, new.market_line, new.market_price, new.opposite_price,
    new.model_fair_line, new.predictive_sd, new.model_prob, new.market_prob,
    new.edge_pct, new.ev_pct, new.stake_units, new.confidence_bucket,
    new.projection_model_version, new.selector_version, new.phase,
    new.publication_scope, new.model_snapshot, new.created_at
  ) then
    raise exception 'nfl_prop_picks issuance fields are immutable';
  end if;
  return new;
end
$$;

alter function public.nfl_prop_freeze_issuance()
  set search_path = pg_catalog, public;

drop trigger if exists nfl_prop_picks_freeze_issuance on public.nfl_prop_picks;
create trigger nfl_prop_picks_freeze_issuance
before update on public.nfl_prop_picks
for each row execute function public.nfl_prop_freeze_issuance();

create or replace function public.nfl_prop_official_requires_trained()
returns trigger
language plpgsql
as $$
declare
  v_ok boolean;
begin
  if new.publication_scope <> 'official' then return new; end if;
  select (m.promoted = true and m.trained = true)
    into v_ok
    from public.nfl_prop_selector_models m
   where m.version = new.selector_version
     and m.market = new.market;
  if coalesce(v_ok, false) <> true then
    raise exception 'official player-prop pick requires promoted trained selector';
  end if;
  return new;
end
$$;

alter function public.nfl_prop_official_requires_trained()
  set search_path = pg_catalog, public;

drop trigger if exists nfl_prop_picks_official_requires_trained on public.nfl_prop_picks;
create trigger nfl_prop_picks_official_requires_trained
before insert on public.nfl_prop_picks
for each row execute function public.nfl_prop_official_requires_trained();

create table if not exists public.nfl_prop_pick_grades (
  pick_id uuid primary key references public.nfl_prop_picks(id) on delete restrict,
  final_value numeric,
  result text not null check (result in ('win','loss','push','void')),
  units_delta numeric not null,
  closing_line numeric,
  closing_price integer,
  closing_opposite_price integer,
  closing_market_prob numeric check (closing_market_prob is null or (closing_market_prob >= 0 and closing_market_prob <= 1)),
  clv_points numeric,
  clv_prob numeric,
  clv_beat boolean,
  brier numeric check (brier is null or (brier >= 0 and brier <= 1)),
  source text not null,
  graded_at timestamptz not null default now()
);

alter table public.nfl_prop_pick_grades enable row level security;

create table if not exists public.nfl_prop_learning_observations (
  pick_id uuid primary key references public.nfl_prop_picks(id) on delete restrict,
  season integer not null,
  week integer not null,
  market text not null,
  phase text not null,
  publication_scope text not null,
  features jsonb not null,
  model_prob numeric not null,
  market_prob numeric,
  edge_pct numeric,
  ev_pct numeric,
  confidence_bucket text,
  outcome smallint check (outcome is null or outcome in (0,1)),
  clv_beat boolean,
  units_delta numeric not null,
  brier numeric,
  finalized_at timestamptz not null,
  is_final boolean not null default true,
  constraint nfl_prop_learning_features_object check (jsonb_typeof(features) = 'object')
);

alter table public.nfl_prop_learning_observations enable row level security;
create index if not exists nfl_prop_learning_market_week_idx
  on public.nfl_prop_learning_observations (market, season, week);

create table if not exists public.nfl_prop_pick_audit_events (
  id bigint generated by default as identity primary key,
  pick_id uuid references public.nfl_prop_picks(id) on delete restrict,
  event_type text not null,
  selector_version bigint,
  detail jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  constraint nfl_prop_audit_detail_object check (jsonb_typeof(detail) = 'object')
);

alter table public.nfl_prop_pick_audit_events enable row level security;
create index if not exists nfl_prop_pick_audit_pick_idx
  on public.nfl_prop_pick_audit_events (pick_id, occurred_at);

create table if not exists public.nfl_prop_pick_receipts (
  seq bigint generated by default as identity primary key,
  pick_id uuid not null unique references public.nfl_prop_picks(id) on delete restrict,
  issued_at timestamptz not null,
  publication_scope text not null check (publication_scope in ('tracking','official')),
  receipt_version text not null default 'pbe-prop-issuance-v1',
  payload jsonb not null,
  payload_sha256 text not null check (payload_sha256 ~ '^[0-9a-f]{64}$'),
  previous_chain_hash text check (previous_chain_hash is null or previous_chain_hash ~ '^[0-9a-f]{64}$'),
  chain_hash text not null unique check (chain_hash ~ '^[0-9a-f]{64}$'),
  created_at timestamptz not null default now()
);

alter table public.nfl_prop_pick_receipts enable row level security;
create index if not exists nfl_prop_pick_receipts_scope_issued_idx
  on public.nfl_prop_pick_receipts (publication_scope, issued_at desc);

create or replace function public.nfl_prop_receipt_no_mutation()
returns trigger
language plpgsql
as $$
begin
  raise exception 'nfl_prop_pick_receipts is append-only';
end
$$;

alter function public.nfl_prop_receipt_no_mutation()
  set search_path = pg_catalog, public;

drop trigger if exists nfl_prop_receipts_no_mutation on public.nfl_prop_pick_receipts;
create trigger nfl_prop_receipts_no_mutation
before update or delete on public.nfl_prop_pick_receipts
for each row execute function public.nfl_prop_receipt_no_mutation();

create or replace function public.nfl_prop_receipt_after_insert()
returns trigger
language plpgsql
as $$
declare
  v_payload jsonb;
  v_payload_hash text;
  v_prev_hash text;
  v_chain_hash text;
begin
  perform pg_advisory_xact_lock(hashtext('nfl_prop_pick_receipts_v1'));

  v_payload := jsonb_build_object(
    'pick_id', new.id,
    'issued_at', new.created_at,
    'event_id', new.event_id,
    'season', new.season,
    'week', new.week,
    'kickoff_ts', new.kickoff_ts,
    'player_name', new.player_name,
    'player_key', new.player_key,
    'market', new.market,
    'side', new.side,
    'book', new.book,
    'book_key', new.book_key,
    'market_line', new.market_line,
    'market_price', new.market_price,
    'opposite_price', new.opposite_price,
    'model_fair_line', new.model_fair_line,
    'predictive_sd', new.predictive_sd,
    'model_prob', new.model_prob,
    'market_prob', new.market_prob,
    'edge_pct', new.edge_pct,
    'ev_pct', new.ev_pct,
    'stake_units', new.stake_units,
    'confidence_bucket', new.confidence_bucket,
    'projection_model_version', new.projection_model_version,
    'selector_version', new.selector_version,
    'phase', new.phase,
    'publication_scope', new.publication_scope,
    'model_snapshot', new.model_snapshot
  );

  v_payload_hash := encode(
    extensions.digest(convert_to(v_payload::text, 'UTF8'), 'sha256'),
    'hex'
  );

  select r.chain_hash into v_prev_hash
    from public.nfl_prop_pick_receipts r
   order by r.seq desc
   limit 1;

  v_chain_hash := encode(
    extensions.digest(
      convert_to(
        coalesce(v_prev_hash, 'GENESIS') || ':' ||
        v_payload_hash || ':' || new.created_at::text || ':' || new.id::text,
        'UTF8'
      ),
      'sha256'
    ),
    'hex'
  );

  insert into public.nfl_prop_pick_receipts (
    pick_id, issued_at, publication_scope, receipt_version,
    payload, payload_sha256, previous_chain_hash, chain_hash
  ) values (
    new.id, new.created_at, new.publication_scope, 'pbe-prop-issuance-v1',
    v_payload, v_payload_hash, v_prev_hash, v_chain_hash
  );
  return new;
end
$$;

alter function public.nfl_prop_receipt_after_insert()
  set search_path = pg_catalog, public, extensions;

drop trigger if exists nfl_prop_pick_issue_receipt on public.nfl_prop_picks;
create trigger nfl_prop_pick_issue_receipt
after insert on public.nfl_prop_picks
for each row execute function public.nfl_prop_receipt_after_insert();

create or replace function public.nfl_replace_open_prop_pick(
  p_open_id uuid,
  p_event_id text,
  p_season integer,
  p_week integer,
  p_kickoff_ts timestamptz,
  p_player_name text,
  p_player_key text,
  p_market text,
  p_side text,
  p_book text,
  p_book_key text,
  p_market_line numeric,
  p_market_price integer,
  p_opposite_price integer,
  p_model_fair_line numeric,
  p_predictive_sd numeric,
  p_model_prob numeric,
  p_market_prob numeric,
  p_edge_pct numeric,
  p_ev_pct numeric,
  p_stake_units numeric,
  p_confidence_bucket text,
  p_projection_model_version text,
  p_selector_version bigint,
  p_phase text,
  p_publication_scope text,
  p_model_snapshot jsonb
) returns uuid
language plpgsql
security definer
as $$
declare
  v_new_id uuid;
begin
  update public.nfl_prop_picks
     set status = 'superseded', closed_at = now()
   where id = p_open_id and status = 'open';
  if not found then raise exception 'open prop pick not found'; end if;

  insert into public.nfl_prop_picks (
    event_id, season, week, kickoff_ts, player_name, player_key,
    market, side, book, book_key, market_line, market_price, opposite_price,
    model_fair_line, predictive_sd, model_prob, market_prob, edge_pct, ev_pct,
    stake_units, confidence_bucket, projection_model_version, selector_version,
    phase, publication_scope, status, model_snapshot
  ) values (
    p_event_id, p_season, p_week, p_kickoff_ts, p_player_name, p_player_key,
    p_market, p_side, p_book, p_book_key, p_market_line, p_market_price, p_opposite_price,
    p_model_fair_line, p_predictive_sd, p_model_prob, p_market_prob, p_edge_pct, p_ev_pct,
    p_stake_units, p_confidence_bucket, p_projection_model_version, p_selector_version,
    p_phase, p_publication_scope, 'open', p_model_snapshot
  ) returning id into v_new_id;

  return v_new_id;
end
$$;

alter function public.nfl_replace_open_prop_pick(
  uuid,text,integer,integer,timestamptz,text,text,text,text,text,text,numeric,
  integer,integer,numeric,numeric,numeric,numeric,numeric,numeric,numeric,text,
  text,bigint,text,text,jsonb
) set search_path = pg_catalog, public;

revoke all on function public.nfl_replace_open_prop_pick(
  uuid,text,integer,integer,timestamptz,text,text,text,text,text,text,numeric,
  integer,integer,numeric,numeric,numeric,numeric,numeric,numeric,numeric,text,
  text,bigint,text,text,jsonb
) from public;

grant execute on function public.nfl_replace_open_prop_pick(
  uuid,text,integer,integer,timestamptz,text,text,text,text,text,text,numeric,
  integer,integer,numeric,numeric,numeric,numeric,numeric,numeric,numeric,text,
  text,bigint,text,text,jsonb
) to service_role;

commit;
