-- Player Prop Engine v1 — local pre-kick closing tape.
-- Captured only while now < kickoff by the selector Worker. The grader uses the
-- last observation before kickoff, never a post-kick market state.

begin;

create table if not exists public.nfl_prop_closing_snapshots (
  id bigint generated by default as identity primary key,
  pick_id uuid not null references public.nfl_prop_picks(id) on delete restrict,
  event_id text not null,
  player_key text not null,
  market text not null,
  book text not null,
  side text not null,
  point numeric,
  price integer,
  opposite_price integer,
  observed_at timestamptz not null,
  captured_at timestamptz not null default now(),
  source text not null default 'pbe-nfl-intelligence'
);

alter table public.nfl_prop_closing_snapshots enable row level security;

create unique index if not exists nfl_prop_close_pick_observed_unique
  on public.nfl_prop_closing_snapshots (pick_id, observed_at);
create index if not exists nfl_prop_close_pick_latest_idx
  on public.nfl_prop_closing_snapshots (pick_id, observed_at desc);

create or replace function public.nfl_prop_close_no_mutation()
returns trigger
language plpgsql
as $$
begin
  raise exception 'nfl_prop_closing_snapshots is append-only';
end
$$;

alter function public.nfl_prop_close_no_mutation()
  set search_path = pg_catalog, public;

drop trigger if exists nfl_prop_close_no_mutation on public.nfl_prop_closing_snapshots;
create trigger nfl_prop_close_no_mutation
before update or delete on public.nfl_prop_closing_snapshots
for each row execute function public.nfl_prop_close_no_mutation();

commit;
