-- PropBetEdge NFL Picks Engine v3 — append-only cryptographic issuance receipts
--
-- This is an INTERNAL tamper-evident ledger, not a third-party notarization.
-- Every pick receives a SHA-256 receipt from the exact immutable issuance
-- payload in the same database transaction that inserts nfl_game_picks.
-- Receipts are chained, RLS-protected, and UPDATE/DELETE are rejected by a
-- trigger. Customer surfaces may expose only the hashes/metadata for OFFICIAL
-- picks; the receipt payload itself remains service-role only.

begin;

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.nfl_pick_receipts (
  seq bigint generated by default as identity primary key,
  pick_id uuid not null unique references public.nfl_game_picks(id) on delete restrict,
  issued_at timestamptz not null,
  publication_scope text not null check (publication_scope in ('tracking','official')),
  receipt_version text not null default 'pbe-issuance-v1',
  payload jsonb not null,
  payload_sha256 text not null check (payload_sha256 ~ '^[0-9a-f]{64}$'),
  previous_chain_hash text check (previous_chain_hash is null or previous_chain_hash ~ '^[0-9a-f]{64}$'),
  chain_hash text not null unique check (chain_hash ~ '^[0-9a-f]{64}$'),
  created_at timestamptz not null default now()
);

alter table public.nfl_pick_receipts enable row level security;

create index if not exists nfl_pick_receipts_scope_issued_idx
  on public.nfl_pick_receipts (publication_scope, issued_at desc);

create or replace function public.nfl_pick_receipt_no_mutation()
returns trigger
language plpgsql
as $$
begin
  raise exception 'nfl_pick_receipts is append-only';
end
$$;

alter function public.nfl_pick_receipt_no_mutation()
  set search_path = pg_catalog, public, extensions;

drop trigger if exists nfl_pick_receipts_no_mutation on public.nfl_pick_receipts;
create trigger nfl_pick_receipts_no_mutation
before update or delete on public.nfl_pick_receipts
for each row execute function public.nfl_pick_receipt_no_mutation();

create or replace function public.nfl_pick_receipt_after_pick_insert()
returns trigger
language plpgsql
as $$
declare
  v_payload jsonb;
  v_payload_hash text;
  v_prev_hash text;
  v_chain_hash text;
begin
  -- Serialize receipt creation so two simultaneous pick inserts cannot fork the
  -- hash chain. The lock lasts only for the current transaction.
  perform pg_advisory_xact_lock(hashtext('nfl_pick_receipts_v1'));

  v_payload := jsonb_build_object(
    'pick_id', new.id,
    'issued_at', new.created_at,
    'game_id', new.game_id,
    'season', new.season,
    'week', new.week,
    'kickoff_ts', new.kickoff_ts,
    'market', new.market,
    'side', new.side,
    'market_line', new.market_line,
    'market_price', new.market_price,
    'model_line', new.model_line,
    'model_prob', new.model_prob,
    'market_prob', new.market_prob,
    'edge_pct', new.edge_pct,
    'stake_units', new.stake_units,
    'confidence_bucket', new.confidence_bucket,
    'model_version', new.model_version,
    'publication_scope', new.publication_scope,
    'selection_team', new.selection_team,
    'selection_over_under', new.selection_over_under,
    'side_is_home', new.side_is_home,
    'features', new.features
  );

  v_payload_hash := encode(
    extensions.digest(convert_to(v_payload::text, 'UTF8'), 'sha256'),
    'hex'
  );

  select r.chain_hash
    into v_prev_hash
    from public.nfl_pick_receipts r
   order by r.seq desc
   limit 1;

  v_chain_hash := encode(
    extensions.digest(
      convert_to(
        coalesce(v_prev_hash, 'GENESIS') || ':' ||
        v_payload_hash || ':' ||
        new.created_at::text || ':' ||
        new.id::text,
        'UTF8'
      ),
      'sha256'
    ),
    'hex'
  );

  insert into public.nfl_pick_receipts (
    pick_id,
    issued_at,
    publication_scope,
    receipt_version,
    payload,
    payload_sha256,
    previous_chain_hash,
    chain_hash
  ) values (
    new.id,
    new.created_at,
    new.publication_scope,
    'pbe-issuance-v1',
    v_payload,
    v_payload_hash,
    v_prev_hash,
    v_chain_hash
  );

  return new;
end
$$;

alter function public.nfl_pick_receipt_after_pick_insert()
  set search_path = pg_catalog, public, extensions;

drop trigger if exists nfl_game_picks_issue_receipt on public.nfl_game_picks;
create trigger nfl_game_picks_issue_receipt
after insert on public.nfl_game_picks
for each row execute function public.nfl_pick_receipt_after_pick_insert();

commit;
