/**
 * Build the ordered migration set for the history database.
 *
 *   node history/deploy/generate.mjs [--check]
 *
 * The schema in history/schema/*.sql is the source of truth. This turns it into
 * numbered migrations, adds the roles/rights policy, and derives one row-level
 * security policy per table so that no table can be added without a rights
 * decision being made for it. --check verifies the committed migrations still
 * match the schema and exits non-zero on drift; it is what the test runs.
 *
 * Nothing here connects to a database.
 */
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, writeFileSync, mkdirSync, existsSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const SCHEMA = join(HERE, '..', 'schema');
const POLICY = join(HERE, 'policy');
const OUT = join(HERE, 'migrations');
const sha = (text) => createHash('sha256').update(text.replace(/\r\n/g, '\n')).digest('hex');

/* ---------------------------------------------------------------- tables */
export function parseTables(sqlText) {
  const tables = [];
  for (const m of sqlText.matchAll(/create table ([\w.]+) \(([\s\S]*?)\n\);/g)) {
    tables.push({ name: m[1], hasSnapshot: /\bsource_snapshot_id\b/.test(m[2]) });
  }
  return tables;
}

/* How a table without its own source_snapshot_id is gated. A table that is not
   listed here and has no snapshot column is refused by the generator: the
   fail-closed default is that new data has no rights decision yet. */
export const RIGHTS_EXCEPTIONS = {
  // Our own rights registry and ontology. Readable on every surface: knowing
  // which sources exist and what we may do with them is not third-party data.
  'football_src.source': { rule: 'always' },
  'football.stat_definition': { rule: 'always' },
  // The identity spine carries no snapshot; its evidence is entity_source_record.
  'football.person': { rule: 'entity', entityType: 'person' },
  'football.player': { rule: 'entity', entityType: 'player', idColumn: 'global_football_player_id' },
  'football.coach': { rule: 'entity', entityType: 'coach', idColumn: 'global_football_coach_id' },
  // Child rows inherit the rights of the row they belong to.
  'football.transaction_asset': { rule: 'parent', parent: 'football.transaction', on: 'transaction_id' },
  'football.depth_chart_entry': { rule: 'parent', parent: 'football.depth_chart_snapshot', on: 'depth_chart_snapshot_id' },
  // A merge decision names the people considered; it is never a public fact.
  'football_src.identity_match_decision': { rule: 'internal_only' },
  // Derived rows may only be published once the derivation records the rights
  // of everything that fed it. Until that exists, derived output is internal.
  'football_derived.derivation': { rule: 'internal_only' },
  'football_derived.leaderboard_entry': { rule: 'internal_only' },
  'football_derived.record': { rule: 'internal_only' },
  'football_derived.game_feature': { rule: 'internal_only' },
};

const ID_COLUMN = { 'football.person': 'global_football_person_id' };

function policyFor(table) {
  const exception = RIGHTS_EXCEPTIONS[table.name];
  if (table.hasSnapshot) return `football_rights.snapshot_visible(source_snapshot_id)`;
  if (!exception) return null;
  switch (exception.rule) {
    case 'always': return 'true';
    case 'internal_only': return `'internal_only' = any (football_rights.current_surface())`;
    case 'entity': {
      const idColumn = exception.idColumn || ID_COLUMN[table.name] || 'id';
      return `football_rights.entity_visible('${exception.entityType}', ${idColumn})`;
    }
    case 'parent':
      return `exists (select 1 from ${exception.parent} p
      where p.${exception.on} = ${table.name.split('.')[1]}.${exception.on}
        and football_rights.snapshot_visible(p.source_snapshot_id))`;
    default: return null;
  }
}

export function buildRightsSql(tables) {
  const lines = [
    '-- GENERATED by history/deploy/generate.mjs — do not edit by hand.',
    '--',
    '-- One row-level security policy per table. Rights filtering happens here,',
    '-- in the data access path, so a query written anywhere — an endpoint, a',
    '-- notebook, a future Worker — cannot return a row the licence does not',
    '-- allow on that surface. A UI filter would only hide it after the fact.',
    '--',
    '-- The owner role bypasses these policies (it loads the data); the reader',
    '-- role the API uses does not.',
    '',
  ];
  const refused = [];
  for (const table of tables) {
    const using = policyFor(table);
    if (!using) { refused.push(table.name); continue; }
    const short = table.name.replace('.', '_');
    lines.push(`alter table ${table.name} enable row level security;`);
    lines.push(`alter table ${table.name} force row level security;`);
    lines.push(`drop policy if exists ${short}_rights on ${table.name};`);
    lines.push(`create policy ${short}_rights on ${table.name} for select to pbe_history_reader`);
    lines.push(`  using (${using});`);
    lines.push('');
  }
  if (refused.length) {
    throw new Error(`no rights rule for: ${refused.join(', ')}\n` +
      'Add a source_snapshot_id column, or an entry in RIGHTS_EXCEPTIONS saying how the table is gated.');
  }
  return lines.join('\n');
}

/* ---------------------------------------------------------------- build */
export function plan() {
  const schemaFiles = readdirSync(SCHEMA).filter(f => f.endsWith('.sql')).sort();
  const tables = [];
  const steps = [];
  let n = 0;
  const next = () => String(++n).padStart(3, '0');

  for (const file of schemaFiles) {
    const body = readFileSync(join(SCHEMA, file), 'utf8');
    tables.push(...parseTables(body));
    steps.push({ name: `${next()}_${file.replace(/^\d+_/, '')}`, body, from: `schema/${file}` });
  }
  const policyFiles = readdirSync(POLICY).filter(f => f.endsWith('.sql')).sort();
  for (const file of policyFiles) {
    steps.push({ name: `${next()}_${file.replace(/^\d+_/, '')}`, body: readFileSync(join(POLICY, file), 'utf8'), from: `deploy/policy/${file}` });
  }
  steps.push({ name: `${next()}_rights_row_level_security.sql`, body: buildRightsSql(tables), from: 'generated' });
  steps.push({ name: `${next()}_deployment_ledger.sql`, body: LEDGER, from: 'generated' });
  return { steps, tables };
}

const LEDGER = `-- GENERATED by history/deploy/generate.mjs — do not edit by hand.
-- What has been applied to this database, so a deployment can be audited and
-- a rollback knows what it is undoing.
create schema if not exists football_deploy;
grant usage on schema football_deploy to pbe_history_owner;

create table if not exists football_deploy.migration (
  filename        text primary key,
  sha256          text not null,
  applied_at      timestamptz not null default now(),
  applied_by      text not null default current_user
);

create table if not exists football_deploy.load (
  load_id         bigserial primary key,
  dataset         text not null,          -- 'skeleton', 'slice2023', 'registry'
  rows_loaded     bigint not null,
  content_sha256  text,
  started_at      timestamptz not null,
  finished_at     timestamptz not null default now(),
  loaded_by       text not null default current_user
);
`;

function main() {
  const check = process.argv.includes('--check');
  const { steps } = plan();
  const manifest = { generated_from: 'history/schema/*.sql + history/deploy/policy/*.sql', steps: [] };
  if (!check) {
    if (existsSync(OUT)) rmSync(OUT, { recursive: true });
    mkdirSync(OUT, { recursive: true });
  }
  let drift = [];
  for (const step of steps) {
    const target = join(OUT, step.name);
    const header = `-- ${step.name}\n-- source: ${step.from}\n-- Generated; apply with history/deploy/apply.mjs, never by hand-editing this file.\n\n`;
    const body = header + step.body.replace(/\r\n/g, '\n').trimEnd() + '\n';
    manifest.steps.push({ filename: step.name, source: step.from, sha256: sha(body) });
    if (check) {
      if (!existsSync(target) || sha(readFileSync(target, 'utf8')) !== sha(body)) drift.push(step.name);
    } else {
      writeFileSync(target, body);
    }
  }
  const manifestText = JSON.stringify(manifest, null, 1) + '\n';
  const manifestPath = join(OUT, 'manifest.json');
  if (check) {
    if (!existsSync(manifestPath) || readFileSync(manifestPath, 'utf8').replace(/\r\n/g, '\n') !== manifestText) drift.push('manifest.json');
    if (drift.length) {
      console.error('migrations are out of date with the schema:', drift.join(', '));
      console.error('run: node history/deploy/generate.mjs');
      process.exit(1);
    }
    console.log(`migrations match the schema (${steps.length} steps)`);
  } else {
    writeFileSync(manifestPath, manifestText);
    console.log(`wrote ${steps.length} migrations to history/deploy/migrations/`);
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
