-- 008_rights_row_level_security.sql
-- source: generated
-- Generated; apply with history/deploy/apply.mjs, never by hand-editing this file.

-- GENERATED by history/deploy/generate.mjs — do not edit by hand.
--
-- One row-level security policy per table. Rights filtering happens here,
-- in the data access path, so a query written anywhere — an endpoint, a
-- notebook, a future Worker — cannot return a row the licence does not
-- allow on that surface. A UI filter would only hide it after the fact.
--
-- The owner role bypasses these policies (it loads the data); the reader
-- role the API uses does not.

alter table football_src.source enable row level security;
alter table football_src.source force row level security;
drop policy if exists football_src_source_rights on football_src.source;
create policy football_src_source_rights on football_src.source for select to pbe_history_reader
  using (true);

alter table football_src.source_lane_policy enable row level security;
alter table football_src.source_lane_policy force row level security;
drop policy if exists football_src_source_lane_policy_rights on football_src.source_lane_policy;
create policy football_src_source_lane_policy_rights on football_src.source_lane_policy for select to pbe_history_reader
  using (true);

alter table football_src.source_snapshot enable row level security;
alter table football_src.source_snapshot force row level security;
drop policy if exists football_src_source_snapshot_rights on football_src.source_snapshot;
create policy football_src_source_snapshot_rights on football_src.source_snapshot for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football_src.entity_source_record enable row level security;
alter table football_src.entity_source_record force row level security;
drop policy if exists football_src_entity_source_record_rights on football_src.entity_source_record;
create policy football_src_entity_source_record_rights on football_src.entity_source_record for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football_src.external_id enable row level security;
alter table football_src.external_id force row level security;
drop policy if exists football_src_external_id_rights on football_src.external_id;
create policy football_src_external_id_rights on football_src.external_id for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.organization enable row level security;
alter table football.organization force row level security;
drop policy if exists football_organization_rights on football.organization;
create policy football_organization_rights on football.organization for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.league enable row level security;
alter table football.league force row level security;
drop policy if exists football_league_rights on football.league;
create policy football_league_rights on football.league for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.league_relation enable row level security;
alter table football.league_relation force row level security;
drop policy if exists football_league_relation_rights on football.league_relation;
create policy football_league_relation_rights on football.league_relation for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.rules_profile enable row level security;
alter table football.rules_profile force row level security;
drop policy if exists football_rules_profile_rights on football.rules_profile;
create policy football_rules_profile_rights on football.rules_profile for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.season enable row level security;
alter table football.season force row level security;
drop policy if exists football_season_rights on football.season;
create policy football_season_rights on football.season for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.competition enable row level security;
alter table football.competition force row level security;
drop policy if exists football_competition_rights on football.competition;
create policy football_competition_rights on football.competition for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.org_unit enable row level security;
alter table football.org_unit force row level security;
drop policy if exists football_org_unit_rights on football.org_unit;
create policy football_org_unit_rights on football.org_unit for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.franchise enable row level security;
alter table football.franchise force row level security;
drop policy if exists football_franchise_rights on football.franchise;
create policy football_franchise_rights on football.franchise for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.team_identity enable row level security;
alter table football.team_identity force row level security;
drop policy if exists football_team_identity_rights on football.team_identity;
create policy football_team_identity_rights on football.team_identity for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.team_identity_franchise enable row level security;
alter table football.team_identity_franchise force row level security;
drop policy if exists football_team_identity_franchise_rights on football.team_identity_franchise;
create policy football_team_identity_franchise_rights on football.team_identity_franchise for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.franchise_lineage_event enable row level security;
alter table football.franchise_lineage_event force row level security;
drop policy if exists football_franchise_lineage_event_rights on football.franchise_lineage_event;
create policy football_franchise_lineage_event_rights on football.franchise_lineage_event for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.team_alignment enable row level security;
alter table football.team_alignment force row level security;
drop policy if exists football_team_alignment_rights on football.team_alignment;
create policy football_team_alignment_rights on football.team_alignment for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.venue enable row level security;
alter table football.venue force row level security;
drop policy if exists football_venue_rights on football.venue;
create policy football_venue_rights on football.venue for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.venue_name enable row level security;
alter table football.venue_name force row level security;
drop policy if exists football_venue_name_rights on football.venue_name;
create policy football_venue_name_rights on football.venue_name for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.venue_attribute_period enable row level security;
alter table football.venue_attribute_period force row level security;
drop policy if exists football_venue_attribute_period_rights on football.venue_attribute_period;
create policy football_venue_attribute_period_rights on football.venue_attribute_period for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.team_home_venue enable row level security;
alter table football.team_home_venue force row level security;
drop policy if exists football_team_home_venue_rights on football.team_home_venue;
create policy football_team_home_venue_rights on football.team_home_venue for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.person enable row level security;
alter table football.person force row level security;
drop policy if exists football_person_rights on football.person;
create policy football_person_rights on football.person for select to pbe_history_reader
  using (football_rights.entity_visible('person', global_football_person_id));

alter table football.player enable row level security;
alter table football.player force row level security;
drop policy if exists football_player_rights on football.player;
create policy football_player_rights on football.player for select to pbe_history_reader
  using (football_rights.entity_visible('player', global_football_player_id));

alter table football.coach enable row level security;
alter table football.coach force row level security;
drop policy if exists football_coach_rights on football.coach;
create policy football_coach_rights on football.coach for select to pbe_history_reader
  using (football_rights.entity_visible('coach', global_football_coach_id));

alter table football.person_name enable row level security;
alter table football.person_name force row level security;
drop policy if exists football_person_name_rights on football.person_name;
create policy football_person_name_rights on football.person_name for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.person_attribute_observation enable row level security;
alter table football.person_attribute_observation force row level security;
drop policy if exists football_person_attribute_observation_rights on football.person_attribute_observation;
create policy football_person_attribute_observation_rights on football.person_attribute_observation for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football_src.identity_match_decision enable row level security;
alter table football_src.identity_match_decision force row level security;
drop policy if exists football_src_identity_match_decision_rights on football_src.identity_match_decision;
create policy football_src_identity_match_decision_rights on football_src.identity_match_decision for select to pbe_history_reader
  using ('internal_only' = any (football_rights.current_surface()));

alter table football.player_position_observation enable row level security;
alter table football.player_position_observation force row level security;
drop policy if exists football_player_position_observation_rights on football.player_position_observation;
create policy football_player_position_observation_rights on football.player_position_observation for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.jersey_number_period enable row level security;
alter table football.jersey_number_period force row level security;
drop policy if exists football_jersey_number_period_rights on football.jersey_number_period;
create policy football_jersey_number_period_rights on football.jersey_number_period for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.school enable row level security;
alter table football.school force row level security;
drop policy if exists football_school_rights on football.school;
create policy football_school_rights on football.school for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.school_name enable row level security;
alter table football.school_name force row level security;
drop policy if exists football_school_name_rights on football.school_name;
create policy football_school_name_rights on football.school_name for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.college_team enable row level security;
alter table football.college_team force row level security;
drop policy if exists football_college_team_rights on football.college_team;
create policy football_college_team_rights on football.college_team for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.college_team_membership enable row level security;
alter table football.college_team_membership force row level security;
drop policy if exists football_college_team_membership_rights on football.college_team_membership;
create policy football_college_team_membership_rights on football.college_team_membership for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.career_stage enable row level security;
alter table football.career_stage force row level security;
drop policy if exists football_career_stage_rights on football.career_stage;
create policy football_career_stage_rights on football.career_stage for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.college_enrollment enable row level security;
alter table football.college_enrollment force row level security;
drop policy if exists football_college_enrollment_rights on football.college_enrollment;
create policy football_college_enrollment_rights on football.college_enrollment for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.combine_measurement enable row level security;
alter table football.combine_measurement force row level security;
drop policy if exists football_combine_measurement_rights on football.combine_measurement;
create policy football_combine_measurement_rights on football.combine_measurement for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.draft enable row level security;
alter table football.draft force row level security;
drop policy if exists football_draft_rights on football.draft;
create policy football_draft_rights on football.draft for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.draft_pick_asset enable row level security;
alter table football.draft_pick_asset force row level security;
drop policy if exists football_draft_pick_asset_rights on football.draft_pick_asset;
create policy football_draft_pick_asset_rights on football.draft_pick_asset for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.draft_selection enable row level security;
alter table football.draft_selection force row level security;
drop policy if exists football_draft_selection_rights on football.draft_selection;
create policy football_draft_selection_rights on football.draft_selection for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.transaction enable row level security;
alter table football.transaction force row level security;
drop policy if exists football_transaction_rights on football.transaction;
create policy football_transaction_rights on football.transaction for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.transaction_asset enable row level security;
alter table football.transaction_asset force row level security;
drop policy if exists football_transaction_asset_rights on football.transaction_asset;
create policy football_transaction_asset_rights on football.transaction_asset for select to pbe_history_reader
  using (exists (select 1 from football.transaction p
      where p.transaction_id = transaction_asset.transaction_id
        and football_rights.snapshot_visible(p.source_snapshot_id)));

alter table football.roster_status_period enable row level security;
alter table football.roster_status_period force row level security;
drop policy if exists football_roster_status_period_rights on football.roster_status_period;
create policy football_roster_status_period_rights on football.roster_status_period for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.depth_chart_snapshot enable row level security;
alter table football.depth_chart_snapshot force row level security;
drop policy if exists football_depth_chart_snapshot_rights on football.depth_chart_snapshot;
create policy football_depth_chart_snapshot_rights on football.depth_chart_snapshot for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.depth_chart_entry enable row level security;
alter table football.depth_chart_entry force row level security;
drop policy if exists football_depth_chart_entry_rights on football.depth_chart_entry;
create policy football_depth_chart_entry_rights on football.depth_chart_entry for select to pbe_history_reader
  using (exists (select 1 from football.depth_chart_snapshot p
      where p.depth_chart_snapshot_id = depth_chart_entry.depth_chart_snapshot_id
        and football_rights.snapshot_visible(p.source_snapshot_id)));

alter table football.coaching_tenure enable row level security;
alter table football.coaching_tenure force row level security;
drop policy if exists football_coaching_tenure_rights on football.coaching_tenure;
create policy football_coaching_tenure_rights on football.coaching_tenure for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.availability_report enable row level security;
alter table football.availability_report force row level security;
drop policy if exists football_availability_report_rights on football.availability_report;
create policy football_availability_report_rights on football.availability_report for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.award enable row level security;
alter table football.award force row level security;
drop policy if exists football_award_rights on football.award;
create policy football_award_rights on football.award for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.award_result enable row level security;
alter table football.award_result force row level security;
drop policy if exists football_award_result_rights on football.award_result;
create policy football_award_result_rights on football.award_result for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.stat_definition enable row level security;
alter table football.stat_definition force row level security;
drop policy if exists football_stat_definition_rights on football.stat_definition;
create policy football_stat_definition_rights on football.stat_definition for select to pbe_history_reader
  using (true);

alter table football.game enable row level security;
alter table football.game force row level security;
drop policy if exists football_game_rights on football.game;
create policy football_game_rights on football.game for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.game_team_score enable row level security;
alter table football.game_team_score force row level security;
drop policy if exists football_game_team_score_rights on football.game_team_score;
create policy football_game_team_score_rights on football.game_team_score for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.game_official enable row level security;
alter table football.game_official force row level security;
drop policy if exists football_game_official_rights on football.game_official;
create policy football_game_official_rights on football.game_official for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.game_weather_observation enable row level security;
alter table football.game_weather_observation force row level security;
drop policy if exists football_game_weather_observation_rights on football.game_weather_observation;
create policy football_game_weather_observation_rights on football.game_weather_observation for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.team_game_stat enable row level security;
alter table football.team_game_stat force row level security;
drop policy if exists football_team_game_stat_rights on football.team_game_stat;
create policy football_team_game_stat_rights on football.team_game_stat for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.player_game_stat enable row level security;
alter table football.player_game_stat force row level security;
drop policy if exists football_player_game_stat_rights on football.player_game_stat;
create policy football_player_game_stat_rights on football.player_game_stat for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.player_game_appearance enable row level security;
alter table football.player_game_appearance force row level security;
drop policy if exists football_player_game_appearance_rights on football.player_game_appearance;
create policy football_player_game_appearance_rights on football.player_game_appearance for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.drive enable row level security;
alter table football.drive force row level security;
drop policy if exists football_drive_rights on football.drive;
create policy football_drive_rights on football.drive for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.play enable row level security;
alter table football.play force row level security;
drop policy if exists football_play_rights on football.play;
create policy football_play_rights on football.play for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.play_participant enable row level security;
alter table football.play_participant force row level security;
drop policy if exists football_play_participant_rights on football.play_participant;
create policy football_play_participant_rights on football.play_participant for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.play_penalty enable row level security;
alter table football.play_penalty force row level security;
drop policy if exists football_play_penalty_rights on football.play_penalty;
create policy football_play_penalty_rights on football.play_penalty for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.player_game_snaps enable row level security;
alter table football.player_game_snaps force row level security;
drop policy if exists football_player_game_snaps_rights on football.player_game_snaps;
create policy football_player_game_snaps_rights on football.player_game_snaps for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football_derived.derivation enable row level security;
alter table football_derived.derivation force row level security;
drop policy if exists football_derived_derivation_rights on football_derived.derivation;
create policy football_derived_derivation_rights on football_derived.derivation for select to pbe_history_reader
  using ('internal_only' = any (football_rights.current_surface()));

alter table football_derived.leaderboard_entry enable row level security;
alter table football_derived.leaderboard_entry force row level security;
drop policy if exists football_derived_leaderboard_entry_rights on football_derived.leaderboard_entry;
create policy football_derived_leaderboard_entry_rights on football_derived.leaderboard_entry for select to pbe_history_reader
  using ('internal_only' = any (football_rights.current_surface()));

alter table football_derived.record enable row level security;
alter table football_derived.record force row level security;
drop policy if exists football_derived_record_rights on football_derived.record;
create policy football_derived_record_rights on football_derived.record for select to pbe_history_reader
  using ('internal_only' = any (football_rights.current_surface()));

alter table football_derived.game_feature enable row level security;
alter table football_derived.game_feature force row level security;
drop policy if exists football_derived_game_feature_rights on football_derived.game_feature;
create policy football_derived_game_feature_rights on football_derived.game_feature for select to pbe_history_reader
  using ('internal_only' = any (football_rights.current_surface()));

alter table football.championship_result enable row level security;
alter table football.championship_result force row level security;
drop policy if exists football_championship_result_rights on football.championship_result;
create policy football_championship_result_rights on football.championship_result for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.college_conference enable row level security;
alter table football.college_conference force row level security;
drop policy if exists football_college_conference_rights on football.college_conference;
create policy football_college_conference_rights on football.college_conference for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.college_conference_membership enable row level security;
alter table football.college_conference_membership force row level security;
drop policy if exists football_college_conference_membership_rights on football.college_conference_membership;
create policy football_college_conference_membership_rights on football.college_conference_membership for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.college_program_season enable row level security;
alter table football.college_program_season force row level security;
drop policy if exists football_college_program_season_rights on football.college_program_season;
create policy football_college_program_season_rights on football.college_program_season for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.player_college_affiliation enable row level security;
alter table football.player_college_affiliation force row level security;
drop policy if exists football_player_college_affiliation_rights on football.player_college_affiliation;
create policy football_player_college_affiliation_rights on football.player_college_affiliation for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));

alter table football.college_to_pro_transition enable row level security;
alter table football.college_to_pro_transition force row level security;
drop policy if exists football_college_to_pro_transition_rights on football.college_to_pro_transition;
create policy football_college_to_pro_transition_rights on football.college_to_pro_transition for select to pbe_history_reader
  using (football_rights.snapshot_visible(source_snapshot_id));
