-- 008_deployment_ledger.sql
-- source: generated
-- Generated; apply with history/deploy/apply.mjs, never by hand-editing this file.

-- GENERATED by history/deploy/generate.mjs — do not edit by hand.
-- What has been applied to this database, so a deployment can be audited and
-- a rollback knows what it is undoing.
create schema if not exists football_deploy;
grant usage on schema football_deploy to pbe_history_owner;

create table if not exists football_deploy.migration (
  filename        text primary key,
  sha256          text not null,
  applied_at      timestamptz not null default now(),
  applied_by      text not null default current_user
);

create table if not exists football_deploy.load (
  load_id         bigserial primary key,
  dataset         text not null,          -- 'skeleton', 'slice2023', 'registry'
  rows_loaded     bigint not null,
  content_sha256  text,
  started_at      timestamptz not null,
  finished_at     timestamptz not null default now(),
  loaded_by       text not null default current_user
);
